In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from scipy.spatial.distance import euclidean

In [28]:
df = pd.read_csv("audit_risk.csv")

In [29]:
df

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,4.18,0.6,2.508,2.50,0.2,0.500,6.68,5.0,0.2,...,0.4,0.0,0.2,0.0,2.4,8.574,0.4,0.5,1.7148,1.0
1,3.89,0.00,0.2,0.000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0.0
2,3.89,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096,0.0
3,3.89,0.00,0.2,0.000,10.80,0.6,6.480,10.80,6.0,0.6,...,0.4,0.0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060,1.0
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.08,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.416,0.4,0.5,0.2832,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,55.57,0.49,0.2,0.098,0.40,0.2,0.080,0.89,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.578,0.4,0.5,0.3156,0.0
772,55.57,0.47,0.2,0.094,0.37,0.2,0.074,0.84,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.568,0.4,0.5,0.3136,0.0
773,55.57,0.24,0.2,0.048,0.04,0.2,0.008,0.28,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.456,0.4,0.5,0.2912,0.0
774,55.57,0.20,0.2,0.040,0.00,0.2,0.000,0.20,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.440,0.4,0.5,0.2880,0.0
775,55.57,0.00,0.2,0.000,0.00,0.2,0.000,0.00,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928,0.0

In [30]:
df.dtypes

Sector_score      float64
PARA_A            float64
Score_A           float64
Risk_A            float64
PARA_B            float64
Score_B           float64
Risk_B            float64
TOTAL             float64
numbers           float64
Score_B.1         float64
Risk_C            float64
Money_Value       float64
Score_MV          float64
Risk_D            float64
District_Loss     float64
PROB              float64
RiSk_E            float64
History           float64
Prob              float64
Risk_F            float64
Score             float64
Inherent_Risk     float64
CONTROL_RISK      float64
Detection_Risk    float64
Audit_Risk        float64
Risk              float64
dtype: object

In [31]:
total_values = df.iloc[:, :-1].size
total_values

19400

In [32]:
values_to_drop = int(total_values * 0.0521)
values_to_drop

1010

In [33]:
# Generate random indices for values to be dropped
drop_indices = np.random.choice(total_values, values_to_drop, replace=False)
dataset = df.iloc[:, :-1]

# Replace the selected values with NaN
dataset.values.flat[drop_indices] = np.nan

In [34]:
df

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,4.18,0.6,2.508,2.50,0.2,0.500,6.68,5.0,0.2,...,0.4,0.0,0.2,0.0,2.4,NaN,NaN,0.5,1.7148,1.0
1,3.89,0.00,0.2,0.000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0.0
2,3.89,0.51,NaN,0.102,0.23,0.2,0.046,0.74,5.0,0.2,...,0.4,0.0,0.2,0.0,NaN,1.548,0.4,0.5,NaN,0.0
3,3.89,0.00,0.2,0.000,10.80,0.6,6.480,10.80,6.0,0.6,...,0.4,0.0,0.2,0.0,4.4,17.530,0.4,NaN,3.5060,1.0
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.08,5.0,0.2,...,0.4,NaN,0.2,0.0,2.0,1.416,0.4,0.5,0.2832,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,55.57,0.49,0.2,0.098,0.40,0.2,0.080,0.89,5.0,0.2,...,0.4,0.0,0.2,0.0,NaN,1.578,0.4,0.5,0.3156,0.0
772,55.57,0.47,0.2,0.094,0.37,0.2,0.074,0.84,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.568,0.4,0.5,0.3136,0.0
773,55.57,0.24,0.2,NaN,0.04,0.2,0.008,NaN,5.0,0.2,...,NaN,NaN,0.2,0.0,2.0,1.456,0.4,0.5,0.2912,0.0
774,55.57,0.20,0.2,0.040,0.00,NaN,0.000,0.20,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.440,0.4,0.5,0.2880,0.0
775,55.57,0.00,0.2,0.000,0.00,0.2,0.000,0.00,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928,0.0

In [35]:
df.isnull().sum()

Sector_score      38
PARA_A            47
Score_A           46
Risk_A            44
PARA_B            46
Score_B           32
Risk_B            43
TOTAL             36
numbers           51
Score_B.1         53
Risk_C            42
Money_Value       45
Score_MV          27
Risk_D            45
District_Loss     33
PROB              32
RiSk_E            37
History           33
Prob              43
Risk_F            45
Score             39
Inherent_Risk     36
CONTROL_RISK      28
Detection_Risk    52
Audit_Risk        37
Risk               0
dtype: int64

In [36]:
null_counts = df.isnull().sum().sum()
total = df.size
null_percentages = 100 * null_counts / total
print("total nilai :",total)
print("nilai hilang :",null_counts)
print("persentase :",null_percentages)

total nilai : 20176
nilai hilang : 1010
persentase : 5.005947660586836

In [37]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

Sector_score      4.896907
PARA_A            6.056701
Score_A           5.927835
Risk_A            5.670103
PARA_B            5.927835
Score_B           4.123711
Risk_B            5.541237
TOTAL             4.639175
numbers           6.572165
Score_B.1         6.829897
Risk_C            5.412371
Money_Value       5.798969
Score_MV          3.479381
Risk_D            5.798969
District_Loss     4.252577
PROB              4.123711
RiSk_E            4.768041
History           4.252577
Prob              5.541237
Risk_F            5.798969
Score             5.025773
Inherent_Risk     4.639175
CONTROL_RISK      3.608247
Detection_Risk    6.701031
Audit_Risk        4.768041
Risk              0.000000
dtype: float64

# Imputasi

In [12]:
def jarak(df2,col):
    euc_dist[col] = []
    euc_dist_append =euc_dist[col].append
    for row in range(df2.shape[0]):
        current = df2.index[df2.iloc[:,col] == 0].tolist()
        current = current[0]
        a = df2.iloc[current,col+1:].tolist()
        b = df2.iloc[current,:col].tolist()
        x1 = b+a
        if(row is not current):
            a=df2.iloc[row,col+1:].tolist()
            b=df2.iloc[row,:col].tolist()
            x2=b+a
        else:
            continue
        dist = euclidean(x1,x2)
        euc_dist_append([dist,df2.iloc[row,col]])
#         print(" x1 = ",x1,"\n x2 = ",x2,"\n distance = ",euc_dist[col])

    lst = list(euc_dist[col])
    lst.sort()
    euc_dist[col] = lst
#     print(euc_dist[col])

In [13]:
def Final(df,col,k):
    terdekat = []
    mean = 0
    minimum = None
    maximum = None
    fuzzy_val = []
    y_list = []
    terdekat_append = terdekat.append
    fuzzy_append = fuzzy_val.append
    
    for val in range(k):
        terdekat_append(euc_dist[col][val])
    
    for x,y in terdekat:
        if (minimum is None or maximum is None):
            minimum = y
            maximum = y
        elif(y<minimum):
            minimum = y
        elif(y>maximum):
            maximum = y
        mean += y
    mean /= len(terdekat)
    print("min : ",minimum)
    print("max : ",maximum)
    print("mean : ",mean)
    
    new_list = []
    for x,y in terdekat:
        print(f"Nilai y: {y}")
        y_list.append(y)
        for i in range(len(y_list)):
            for j in range(i+1, len(y_list)):
                if y_list[i] == y_list[j] and y_list[i] not in new_list:
                    new_list.append(y_list[i])
                else:
                    fuzzy_append((y,fuzzy_triangular(y,minimum,mean,maximum)))
#         if len(set(y_list)) == 1:
#             print("Setiap nilai di dalam daftar sama")
#         else:
#             print("Ada setidaknya 2 nilai yang berbeda di dalam daftar")
            
#         print(f"terdekat = {terdekat}")
#         print(f"y = {terdekat[0:][0]}")
        
    print("new_list:",new_list)
#     print("y_list :", y_list)
    print("fuzzy : ",fuzzy_val)
    
    pembilang = 0
    penyebut = 0
#     y = 1
    for nilai,bobot in fuzzy_val:
        pembilang += nilai*bobot
        penyebut += bobot
        
#         if (penyebut == 0):
#             penyebut = y
            
    print("pembilang : ", pembilang)
    print("penyebut : ",penyebut)
    tertimbang = pembilang/penyebut
    print("rata-rata tertimbang : ",tertimbang)
    index = dummy.index[dummy.iloc[:,col] == 0].tolist()
    index = index[0]
    dummy.iloc[index,col] = tertimbang

In [14]:
def fuzzy_triangular(val, minimum, mean, maximum):
   if val <= minimum or val >= maximum: 
        return 0.0
   elif minimum < val <= mean:
        return float((val - minimum)/(mean - minimum)) 
   elif mean < val < maximum:
        return float((maximum - val)/(maximum - mean))

In [15]:
df2 = df.copy()
dummy = df2.fillna(0)
dummy

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,0.00,0.6,2.508,2.50,0.2,0.000,6.68,5.0,0.2,...,0.4,0.0,0.2,0.0,2.4,8.574,0.4,0.5,1.7148,1.0
1,0.00,0.00,0.2,0.000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0.0
2,3.89,0.51,0.0,0.102,0.23,0.2,0.046,0.00,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096,0.0
3,3.89,0.00,0.2,0.000,0.00,0.6,6.480,10.80,6.0,0.6,...,0.4,0.0,0.2,0.0,4.4,17.530,0.4,0.0,3.5060,1.0
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.08,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.416,0.4,0.5,0.2832,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,55.57,0.49,0.2,0.098,0.40,0.2,0.000,0.00,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.578,0.4,0.5,0.3156,0.0
772,55.57,0.47,0.2,0.094,0.37,0.2,0.000,0.84,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.568,0.4,0.5,0.3136,0.0
773,55.57,0.24,0.2,0.048,0.04,0.2,0.008,0.28,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.456,0.0,0.0,0.2912,0.0
774,55.57,0.00,0.2,0.040,0.00,0.2,0.000,0.20,5.0,0.2,...,0.0,0.0,0.2,0.0,2.0,1.440,0.4,0.5,0.2880,0.0
775,55.57,0.00,0.2,0.000,0.00,0.2,0.000,0.00,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928,0.0

In [16]:
dummy.fillna(0, inplace=True)

In [17]:
dummy.isnull().sum()

Sector_score      0
PARA_A            0
Score_A           0
Risk_A            0
PARA_B            0
Score_B           0
Risk_B            0
TOTAL             0
numbers           0
Score_B.1         0
Risk_C            0
Money_Value       0
Score_MV          0
Risk_D            0
District_Loss     0
PROB              0
RiSk_E            0
History           0
Prob              0
Risk_F            0
Score             0
Inherent_Risk     0
CONTROL_RISK      0
Detection_Risk    0
Audit_Risk        0
Risk              0
dtype: int64

In [18]:
euc_dist = {}

In [19]:
for i in range(dummy.shape[1]):
    current = dummy.index[dummy.iloc[:,i] == 0].tolist()
    for x in current:
        jarak(dummy,i)
        Final(dummy,i,5)

min :  55.57
max :  55.57
mean :  55.57000000000001
Nilai y: 55.57
Nilai y: 55.57
Nilai y: 55.57
Nilai y: 55.57
Nilai y: 55.57
new_list: [55.57]
fuzzy :  [(55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0), (55.57, 0.0)]
pembilang :  0.0
penyebut :  0.0
rata-rata tertimbang :  nan

C:\Users\User\AppData\Local\Temp\ipykernel_7968\1204306491.py:62: RuntimeWarning: invalid value encountered in double_scalars
  tertimbang = pembilang/penyebut

min :  0.0
max :  3.41
mean :  2.5900000000000003
Nilai y: 3.41
Nilai y: 3.41
Nilai y: 0.0
Nilai y: 2.72
Nilai y: 3.41
new_list: [3.41]
fuzzy :  [(0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (2.72, 0.8414634146341464), (2.72, 0.8414634146341464), (2.72, 0.8414634146341464), (2.72, 0.8414634146341464), (2.72, 0.8414634146341464), (2.72, 0.8414634146341464), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0)]
pembilang :  13.73268292682927
penyebut :  5.048780487804879
rata-rata tertimbang :  2.7199999999999998
min :  2.72
max :  3.41
mean :  3.1340000000000003
Nilai y: 3.41
Nilai y: 3.41
Nilai y: 2.72
Nilai y: 2.72
Nilai y: 3.41
new_list: [3.41, 2.72]
fuzzy :  [(2.72, 0.0), (2.72, 0.0), (2.72, 0.0), (2.72, 0.0), (2.72, 0.0), (2.72, 0.0), (2.72, 0.0), (2.72, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0)]
pembilang :  0.0
penyebut :  0.0
rata-rata tertimbang :  nan
min :  0.0
max :  3.89
mean :  2.644
Nilai y: 2.72
Nilai y: 3.89
Nilai y: 2.72
Nilai y: 3.89
Nilai y: 0.0
new_list: [2.72, 3.89]
fuzzy :  [(3.89, 0.0), (2.72, 0.9390048154093097), (2.72, 0.9390048154093097), (3.89, 0.0), (3.89, 0.0), (3.89, 0.0), (3.89, 0.0), (3.89, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0)]
pembilang :  5.1081861958266455
penyebut :  1.8780096308186194
rata-rata tertimbang :  2.72
min :  1.99
max :  59.85
mean :  46.566
Nilai y: 59.85
Nilai y: 55.57
Nilai y: 59.85
Nilai y: 1.99
Nilai y: 55.57
new_list: [59.85, 55.57]
fuzzy :  [(55.57, 0.3221921108099971), (59.85, 0.0), (59.85, 0.0), (1.99, 0.0), (1.99, 0.0), (1.99, 0.0), (1.99, 0.0), (1.99, 0.0), (1.99, 0.0), (55.57, 0.3221921108099971), (55.57, 0.3221921108099971), (55.57, 0.3221921108099971), (55.57, 0.3221921108099971), (55.57, 0.3221921108099971), (55.57, 0.3221921108099971), (55.57, 0.3221921108099971), (55.57, 0.3221921108099971), (55.57, 0.3221921108099971)]
pembilang :  179.04215597711536
penyebut :  3.2219211080999703
rata-rata tertimbang :  55.57
min :  1.85
max :  3.89
mean :  3.2900000000000005
Nilai y: 3.89
Nilai y: 3.89
Nilai y: 1.85
Nilai y: 3.41
Nilai y: 3.41
new_list: [3.89, 3.41]
fuzzy :  [(1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005), (3.41, 0.8000000000000005)]
pembilang :  40.92000000000003
penyebut :  12.000000000000009
rata-rata tertimbang :  3.41
min :  2.7199999999999998
max :  3.41
mean :  2.996
Nilai y: 2.72
Nilai y: 2.7199999999999998
Nilai y: 3.41
Nilai y: 2.72
Nilai y: 3.41
new_list: [2.72, 3.41]
fuzzy :  [(2.7199999999999998, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (2.72, 1.6090188762683415e-15), (2.72, 1.6090188762683415e-15), (2.72, 1.6090188762683415e-15), (2.72, 1.6090188762683415e-15), (2.72, 1.6090188762683415e-15), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0), (3.41, 0.0)]
pembilang :  2.1882656717249446e-14
penyebut :  8.045094381341708e-15
rata-rata tertimbang :  2.72
min :  1.85
max :  1.85
mean :  1.85
Nilai y: 1.85
Nilai y: 1.85
Nilai y: 1.85
Nilai y: 1.85
Nilai y: 1.85
new_list: [1.85]
fuzzy :  [(1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0), (1.85, 0.0)]
pembilang :  0.0
penyebut :  0.0
rata-rata tertimbang :  nan

KeyboardInterrupt:

In [ ]:
dummy

In [ ]:
dummy.describe()

# Klasifikasi

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [ ]:
x = dummy.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [ ]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

In [ ]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

In [ ]:
classifier = KNeighborsClassifier(n_neighbors=7, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

In [ ]:
classifier = KNeighborsClassifier(n_neighbors=9, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

In [ ]:
classifier = KNeighborsClassifier(n_neighbors=11, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)