In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from scipy.spatial.distance import euclidean

In [2]:
df = pd.read_csv("audit_risk.csv")

In [3]:
df

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,4.18,0.6,2.508,2.50,0.2,0.500,6.68,5.0,0.2,...,0.4,0.0,0.2,0.0,2.4,8.574,0.4,0.5,1.7148,1.0
1,3.89,0.00,0.2,0.000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0.0
2,3.89,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096,0.0
3,3.89,0.00,0.2,0.000,10.80,0.6,6.480,10.80,6.0,0.6,...,0.4,0.0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060,1.0
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.08,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.416,0.4,0.5,0.2832,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,55.57,0.49,0.2,0.098,0.40,0.2,0.080,0.89,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.578,0.4,0.5,0.3156,0.0
772,55.57,0.47,0.2,0.094,0.37,0.2,0.074,0.84,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.568,0.4,0.5,0.3136,0.0
773,55.57,0.24,0.2,0.048,0.04,0.2,0.008,0.28,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.456,0.4,0.5,0.2912,0.0
774,55.57,0.20,0.2,0.040,0.00,0.2,0.000,0.20,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.440,0.4,0.5,0.2880,0.0
775,55.57,0.00,0.2,0.000,0.00,0.2,0.000,0.00,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928,0.0

In [4]:
df.dtypes

Sector_score      float64
PARA_A            float64
Score_A           float64
Risk_A            float64
PARA_B            float64
Score_B           float64
Risk_B            float64
TOTAL             float64
numbers           float64
Score_B.1         float64
Risk_C            float64
Money_Value       float64
Score_MV          float64
Risk_D            float64
District_Loss     float64
PROB              float64
RiSk_E            float64
History           float64
Prob              float64
Risk_F            float64
Score             float64
Inherent_Risk     float64
CONTROL_RISK      float64
Detection_Risk    float64
Audit_Risk        float64
Risk              float64
dtype: object

In [5]:
total_values = df.iloc[:, :-1].size
total_values

19400

In [6]:
values_to_drop = int(total_values * 0.05)
values_to_drop

970

In [7]:
# Generate random indices for values to be dropped
drop_indices = np.random.choice(total_values, values_to_drop, replace=False)
dataset = df.iloc[:, :-1]

# Replace the selected values with NaN
dataset.values.flat[drop_indices] = np.nan

In [8]:
df

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,4.18,0.6,2.508,NaN,0.2,0.500,6.68,5.0,NaN,...,0.4,0.0,0.2,0.0,2.4,8.574,0.4,0.5,1.7148,1.0
1,3.89,0.00,NaN,0.000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,NaN,0.0
2,3.89,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,0.2,...,0.4,0.0,0.2,NaN,2.0,1.548,0.4,0.5,0.3096,0.0
3,NaN,0.00,0.2,0.000,10.80,NaN,6.480,10.80,6.0,0.6,...,0.4,0.0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060,1.0
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.08,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.416,0.4,0.5,0.2832,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,55.57,0.49,NaN,0.098,0.40,0.2,0.080,0.89,5.0,0.2,...,NaN,0.0,0.2,0.0,NaN,1.578,0.4,0.5,0.3156,0.0
772,55.57,0.47,0.2,0.094,0.37,0.2,0.074,0.84,5.0,0.2,...,0.4,0.0,0.2,0.0,NaN,1.568,0.4,0.5,0.3136,0.0
773,55.57,0.24,0.2,0.048,0.04,0.2,0.008,0.28,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.456,0.4,0.5,0.2912,0.0
774,55.57,0.20,0.2,0.040,0.00,0.2,0.000,0.20,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.440,0.4,NaN,0.2880,0.0
775,55.57,0.00,0.2,0.000,0.00,0.2,0.000,0.00,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928,0.0

In [9]:
df.isnull().sum()

Sector_score      34
PARA_A            37
Score_A           40
Risk_A            44
PARA_B            27
Score_B           45
Risk_B            26
TOTAL             37
numbers           27
Score_B.1         49
Risk_C            36
Money_Value       41
Score_MV          39
Risk_D            35
District_Loss     34
PROB              43
RiSk_E            46
History           42
Prob              31
Risk_F            48
Score             38
Inherent_Risk     43
CONTROL_RISK      49
Detection_Risk    40
Audit_Risk        39
Risk               0
dtype: int64

In [40]:
null_counts = df.isnull().sum().sum()
total = df.size
null_percentages = 100 * null_counts / total
print("nilai hilang :",null_counts)
print("persentase :",null_percentages)

nilai hilang : 970
persentase : 4.8076923076923075

In [42]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

Sector_score      5.412371
PARA_A            4.381443
Score_A           4.896907
Risk_A            4.381443
PARA_B            5.927835
Score_B           5.541237
Risk_B            5.283505
TOTAL             3.994845
numbers           5.798969
Score_B.1         4.768041
Risk_C            5.154639
Money_Value       5.412371
Score_MV          5.412371
Risk_D            4.381443
District_Loss     5.283505
PROB              4.510309
RiSk_E            5.541237
History           5.927835
Prob              3.737113
Risk_F            5.412371
Score             4.123711
Inherent_Risk     4.768041
CONTROL_RISK      4.123711
Detection_Risk    5.412371
Audit_Risk        5.412371
Risk              0.000000
dtype: float64

# Imputasi

In [43]:
def jarak(df2,col):
    euc_dist[col] = []
    for row in range(df2.shape[0]):
        current = df2.index[df2.iloc[:,col] == 0].tolist()
        current = current[0]
        a = df2.iloc[current,col+1:].tolist()
        b = df2.iloc[current,:col].tolist()
        x1 = b+a
        if(row is not current):
            a=df2.iloc[row,col+1:].tolist()
            b=df2.iloc[row,:col].tolist()
            x2=b+a
        else:
            continue
        dist = euclidean(x1,x2)
        euc_dist[col].append([dist,df2.iloc[row,col]])
#         print(" x1 = ",x1,"\n x2 = ",x2,"\n distance = ",euc_dist[col])

    lst = list(euc_dist[col])
    lst.sort()
    euc_dist[col] = lst
#     print(euc_dist[col])

In [49]:
def Final(df,col,k):
    terdekat = []
    mean = 0
    minimum = None
    maximum = None
    fuzzy_val = []
    
    for val in range(k):
        terdekat.append(euc_dist[col][val])
    
    for x,y in terdekat:
        if (minimum is None or maximum is None):
            minimum = y
            maximum = y
        elif(y<minimum):
            minimum = y
        elif(y>maximum):
            maximum = y
        mean += y
    mean /= len(terdekat)
    for x,y in terdekat:
        fuzzy_val.append((y,fuzzy_triangular(y,minimum,mean,maximum)))

    pembilang = 0
    penyebut = 0
    y = 1
    for nilai,bobot in fuzzy_val:
        pembilang += nilai*bobot
        penyebut += bobot
        
        if (penyebut == 0):
            penyebut = y
    
    tertimbang = pembilang/penyebut
    index = dummy.index[dummy.iloc[:,col] == 0].tolist()
    index = index[0]
    dummy.iloc[index,col] = tertimbang

In [50]:
def fuzzy_triangular(val, minimum, mean, maximum):
   if val <= minimum or val >= maximum: 
        return 0.0
   elif minimum < val <= mean:
        return float((val - minimum)/(mean - minimum)) 
   elif mean < val < maximum:
        return float((maximum - val)/(maximum - mean))

In [51]:
df2 = dataset.copy()
dummy = df2.fillna(0)
dummy

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,PROB,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk
0,3.89,4.18,0.6,2.508,2.50,0.2,0.500,6.68,5.0,0.0,...,0.2,0.4,0.0,0.2,0.0,2.4,8.574,0.4,0.5,1.7148
1,3.89,0.00,0.2,0.000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.0,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.0000
2,3.89,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096
3,3.89,0.00,0.0,0.000,10.80,0.6,0.000,10.80,6.0,0.6,...,0.2,0.4,0.0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060
4,3.89,0.00,0.0,0.000,0.08,0.2,0.016,0.08,5.0,0.0,...,0.2,0.4,0.0,0.2,0.0,2.0,0.000,0.4,0.5,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,55.57,0.49,0.2,0.098,0.40,0.2,0.080,0.89,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.578,0.4,0.5,0.3156
772,55.57,0.47,0.2,0.094,0.37,0.2,0.074,0.84,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.568,0.4,0.5,0.3136
773,55.57,0.24,0.2,0.048,0.04,0.2,0.008,0.28,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.456,0.4,0.0,0.2912
774,55.57,0.20,0.2,0.040,0.00,0.2,0.000,0.20,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.440,0.4,0.5,0.2880
775,55.57,0.00,0.2,0.000,0.00,0.2,0.000,0.00,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928

In [52]:
euc_dist = {}

In [53]:
for i in range(df2.shape[1]):
    current = dummy.index[dummy.iloc[:,i] == 0].tolist()
    for x in current:
        jarak(dummy,i)
        Final(dummy,i,7)

In [54]:
dummy

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,PROB,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk
0,3.89,4.180000,0.6,2.508000,2.50,0.2,0.500000,6.68,5.0,0.0,...,0.2,0.4,0.0,0.2,0.0,2.4,8.574000,0.4,0.5,1.714800
1,3.89,0.580691,0.2,0.065068,4.83,0.2,0.966000,4.83,5.0,0.2,...,0.0,0.4,0.0,0.2,0.0,2.0,2.554000,0.4,0.5,0.604445
2,3.89,0.510000,0.2,0.102000,0.23,0.2,0.046000,0.74,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.548000,0.4,0.5,0.309600
3,3.89,3.686763,0.0,2.202948,10.80,0.6,2.348421,10.80,6.0,0.6,...,0.2,0.4,0.0,0.2,0.0,4.4,17.530000,0.4,0.5,3.506000
4,3.89,0.000000,0.0,0.000000,0.08,0.2,0.016000,0.08,5.0,0.0,...,0.2,0.4,0.0,0.2,0.0,2.0,1.414588,0.4,0.5,0.284706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,55.57,0.490000,0.2,0.098000,0.40,0.2,0.080000,0.89,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.578000,0.4,0.5,0.315600
772,55.57,0.470000,0.2,0.094000,0.37,0.2,0.074000,0.84,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.568000,0.4,0.5,0.313600
773,55.57,0.240000,0.2,0.048000,0.04,0.2,0.008000,0.28,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.456000,0.4,0.0,0.291200
774,55.57,0.200000,0.2,0.040000,0.00,0.2,0.000000,0.20,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.440000,0.4,0.5,0.288000
775,55.57,0.000000,0.2,0.000000,0.00,0.2,0.000000,0.00,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.464000,0.4,0.5,0.292800

In [55]:
dummy.describe()

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,PROB,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk
count,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,...,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000
mean,18.884050,2.365010,0.337629,1.274000,10.429074,0.298196,6.077822,13.169054,4.774485,0.212887,...,0.196134,0.489691,0.099227,0.207732,0.053093,2.626284,17.486438,0.546496,0.472938,7.200172
std,23.961306,5.669281,0.187414,3.225591,49.931554,0.180885,30.007163,51.238789,1.213385,0.091659,...,0.054101,0.306484,0.524693,0.076989,0.305588,0.949074,54.590653,0.448690,0.113204,38.681144
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.539178,0.000000,0.000000,0.000000
25%,2.370000,0.067500,0.200000,0.014000,0.000000,0.200000,0.000000,0.560000,5.000000,0.200000,...,0.200000,0.400000,0.000000,0.200000,0.000000,2.000000,1.575500,0.400000,0.500000,0.315500
50%,3.410000,0.815000,0.200000,0.164000,0.350000,0.200000,0.056000,1.410000,5.000000,0.200000,...,0.200000,0.400000,0.000000,0.200000,0.000000,2.200000,2.200000,0.400000,0.500000,0.517401
75%,55.570000,2.322500,0.600000,1.441500,3.067500,0.400000,1.024500,7.638430,5.000000,0.200000,...,0.200000,0.400000,0.000000,0.200000,0.000000,3.200000,10.782000,0.400000,0.500000,3.260573
max,59.850000,85.000000,0.600000,51.000000,1264.630000,0.600000,758.778000,1268.910000,9.000000,0.600000,...,0.600000,2.400000,9.000000,0.600000,5.400000,5.200000,801.262000,5.800000,0.500000,961.514400

# Klasifikasi

In [56]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [57]:
x = dummy.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [58]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [59]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [60]:
classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[124   0]
 [  7  63]]
0.9639175257731959

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [61]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[124   0]
 [  7  63]]
0.9639175257731959

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [62]:
classifier = KNeighborsClassifier(n_neighbors=7, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[124   0]
 [ 10  60]]
0.9484536082474226

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [63]:
classifier = KNeighborsClassifier(n_neighbors=9, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[124   0]
 [ 12  58]]
0.9381443298969072

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [64]:
classifier = KNeighborsClassifier(n_neighbors=11, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[124   0]
 [ 13  57]]
0.9329896907216495

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)