In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("audit_5%.csv")

In [3]:
df

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,4.18,0.6,2.508,2.50,0.2,0.500,6.68,5.0,0.2,...,NaN,0.0,0.2,0.0,2.4,8.574,0.4,0.5,NaN,1.0
1,NaN,0.00,NaN,0.000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0.0
2,3.89,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096,0.0
3,3.89,0.00,0.2,NaN,10.80,0.6,6.480,NaN,6.0,0.6,...,0.4,0.0,0.2,NaN,4.4,17.530,0.4,0.5,3.5060,1.0
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.08,NaN,0.2,...,0.4,NaN,NaN,0.0,2.0,1.416,0.4,0.5,0.2832,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,NaN,0.49,0.2,0.098,0.40,0.2,0.080,0.89,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.578,0.4,NaN,0.3156,0.0
772,55.57,0.47,0.2,0.094,0.37,0.2,0.074,0.84,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.568,0.4,0.5,0.3136,0.0
773,55.57,0.24,0.2,NaN,0.04,0.2,0.008,0.28,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.456,0.4,0.5,0.2912,0.0
774,55.57,0.20,0.2,0.040,0.00,0.2,0.000,0.20,NaN,0.2,...,0.4,0.0,0.2,0.0,2.0,1.440,0.4,0.5,0.2880,0.0
775,55.57,0.00,0.2,0.000,0.00,0.2,NaN,0.00,5.0,0.2,...,NaN,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928,0.0

In [4]:
df.dtypes

Sector_score      float64
PARA_A            float64
Score_A           float64
Risk_A            float64
PARA_B            float64
Score_B           float64
Risk_B            float64
TOTAL             float64
numbers           float64
Score_B.1         float64
Risk_C            float64
Money_Value       float64
Score_MV          float64
Risk_D            float64
District_Loss     float64
PROB              float64
RiSk_E            float64
History           float64
Prob              float64
Risk_F            float64
Score             float64
Inherent_Risk     float64
CONTROL_RISK      float64
Detection_Risk    float64
Audit_Risk        float64
Risk              float64
dtype: object

In [5]:
df.isnull().sum()

Sector_score      56
PARA_A            46
Score_A           38
Risk_A            46
PARA_B            43
Score_B           39
Risk_B            46
TOTAL             34
numbers           38
Score_B.1         26
Risk_C            41
Money_Value       43
Score_MV          35
Risk_D            35
District_Loss     24
PROB              45
RiSk_E            48
History           48
Prob              43
Risk_F            40
Score             37
Inherent_Risk     33
CONTROL_RISK      35
Detection_Risk    42
Audit_Risk        49
Risk               0
dtype: int64

In [6]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

Sector_score      7.216495
PARA_A            5.927835
Score_A           4.896907
Risk_A            5.927835
PARA_B            5.541237
Score_B           5.025773
Risk_B            5.927835
TOTAL             4.381443
numbers           4.896907
Score_B.1         3.350515
Risk_C            5.283505
Money_Value       5.541237
Score_MV          4.510309
Risk_D            4.510309
District_Loss     3.092784
PROB              5.798969
RiSk_E            6.185567
History           6.185567
Prob              5.541237
Risk_F            5.154639
Score             4.768041
Inherent_Risk     4.252577
CONTROL_RISK      4.510309
Detection_Risk    5.412371
Audit_Risk        6.314433
Risk              0.000000
dtype: float64

In [7]:
null_counts = df.isnull().sum().sum()
total = df.size
null_percentages = 100 * null_counts / total
print("total nilai :",total)
print("nilai hilang :",null_counts)
print("persentase hilang :",null_percentages)

total nilai : 20176
nilai hilang : 1010
persentase hilang : 5.005947660586836

# Imputasi Median

In [8]:
df2 = df.fillna(df.median())

In [9]:
df2

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,4.18,0.6,2.508,2.50,0.2,0.500,6.680,5.0,0.2,...,0.4,0.0,0.2,0.0,2.4,8.574,0.4,0.5,0.5028,1.0
1,3.89,0.00,0.2,0.000,4.83,0.2,0.966,4.830,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0.0
2,3.89,0.51,0.2,0.102,0.23,0.2,0.046,0.740,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096,0.0
3,3.89,0.00,0.2,0.175,10.80,0.6,6.480,1.365,6.0,0.6,...,0.4,0.0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060,1.0
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.080,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.416,0.4,0.5,0.2832,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,3.89,0.49,0.2,0.098,0.40,0.2,0.080,0.890,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.578,0.4,0.5,0.3156,0.0
772,55.57,0.47,0.2,0.094,0.37,0.2,0.074,0.840,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.568,0.4,0.5,0.3136,0.0
773,55.57,0.24,0.2,0.175,0.04,0.2,0.008,0.280,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.456,0.4,0.5,0.2912,0.0
774,55.57,0.20,0.2,0.040,0.00,0.2,0.000,0.200,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.440,0.4,0.5,0.2880,0.0
775,55.57,0.00,0.2,0.000,0.00,0.2,0.078,0.000,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928,0.0

In [10]:
df2.describe()

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
count,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,...,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.0,776.000000,776.000000
mean,19.021005,2.271612,0.344845,1.293624,10.281416,0.308763,6.058462,12.718855,5.063789,0.222938,...,0.511340,0.100515,0.216495,0.052577,2.666753,17.044519,0.565979,0.5,6.680907,0.393041
std,23.810874,4.699168,0.172867,3.414958,49.849787,0.167949,30.000082,51.193382,0.258013,0.078959,...,0.278568,0.528125,0.067670,0.305339,0.837278,54.527417,0.440384,0.0,38.267287,0.488741
min,1.850000,0.000000,0.200000,0.000000,0.000000,0.200000,0.000000,0.000000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.000000,1.400000,0.400000,0.5,0.280000,0.000000
25%,2.370000,0.270000,0.200000,0.058000,0.000000,0.200000,0.000000,0.590000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.000000,1.590000,0.400000,0.5,0.319200,0.000000
50%,3.890000,0.880000,0.200000,0.175000,0.410000,0.200000,0.078000,1.365000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.200000,2.200000,0.400000,0.5,0.502800,0.000000
75%,55.570000,2.422500,0.600000,1.351500,2.845000,0.400000,0.966000,7.115000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,3.200000,8.991500,0.400000,0.5,2.692200,1.000000
max,59.850000,85.000000,0.600000,51.000000,1264.630000,0.600000,758.778000,1268.910000,9.000000,0.600000,...,2.400000,9.000000,0.600000,5.400000,5.200000,801.262000,5.800000,0.5,961.514400,1.000000

# Klasifikasi

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [12]:
x = df2.iloc[:, :-1].values
y = df2.iloc[:, -1].values

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=32)

In [14]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [15]:
classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[104   3]
 [ 11  76]]
0.9278350515463918

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [16]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[104   3]
 [ 12  75]]
0.9226804123711341

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [17]:
classifier = KNeighborsClassifier(n_neighbors=7, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[105   2]
 [ 14  73]]
0.9175257731958762

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [18]:
classifier = KNeighborsClassifier(n_neighbors=9, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[105   2]
 [ 14  73]]
0.9175257731958762

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)