In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("onehr.csv")

In [3]:
df

,date,WSR0,WSR1,WSR2,WSR3,WSR4,WSR5,WSR6,WSR7,WSR8,...,RH50,U50,V50,HT50,KI,TT,SLP,SLP_,Precp,Class
0,1/1/1998,0.8,1.8,2.4,2.1,2.0,2.1,1.5,1.7,1.9,...,0.15,10.67,-1.56,5795.0,-12.10,17.9,10330.0,-55.0,0.00,0
1,1/2/1998,2.8,3.2,3.3,2.7,3.3,3.2,2.9,2.8,3.1,...,0.48,8.39,3.84,5805.0,14.05,29.0,10275.0,-55.0,0.00,0
2,1/3/1998,2.9,2.8,2.6,2.1,2.2,2.5,2.5,2.7,2.2,...,0.60,6.94,9.80,5790.0,17.90,41.3,10235.0,-40.0,0.00,0
3,1/4/1998,4.7,3.8,3.7,3.8,2.9,3.1,2.8,2.5,2.4,...,0.49,8.73,10.54,5775.0,31.15,51.7,10195.0,-40.0,2.08,0
4,1/5/1998,2.6,2.1,1.6,1.4,0.9,1.5,1.2,1.4,1.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.58,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1094,1/10/2001,2.1,2.7,1.8,2.5,4.1,3.5,3.8,3.9,3.9,...,0.48,9.48,5.72,5745.0,-18.60,13.1,10270.0,40.0,3.63,0
1095,1/11/2001,1.5,1.5,1.4,1.9,2.6,2.3,2.7,2.9,2.6,...,0.48,24.56,12.41,5710.0,15.20,41.5,10180.0,-90.0,0.00,0
1096,1/12/2001,2.5,1.7,1.4,1.5,1.6,1.6,1.3,1.1,0.9,...,0.02,23.19,-9.94,5770.0,-20.70,31.7,10210.0,30.0,0.00,0
1097,1/13/2001,3.0,3.0,3.1,4.6,2.4,1.7,2.4,3.0,3.2,...,0.56,18.23,3.95,5795.0,-29.50,16.9,10220.0,10.0,0.18,0
1098,1/14/2001,0.8,0.8,0.9,0.8,1.2,1.0,1.7,1.7,1.5,...,0.04,22.46,8.17,5775.0,21.30,45.4,10170.0,-50.0,0.03,0

In [4]:
df.dtypes

date      object
WSR0     float64
WSR1     float64
WSR2     float64
WSR3     float64
          ...
TT       float64
SLP      float64
SLP_     float64
Precp    float64
Class      int64
Length: 74, dtype: object

In [5]:
df.drop('date', axis=1, inplace=True)

In [6]:
df.isnull().sum()

WSR0      27
WSR1      27
WSR2      28
WSR3      27
WSR4      27
        ...
TT        76
SLP       61
SLP_     107
Precp      0
Class      0
Length: 73, dtype: int64

In [7]:
df.isnull().sum().sum()

2272

In [8]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

WSR0     2.456779
WSR1     2.456779
WSR2     2.547771
WSR3     2.456779
WSR4     2.456779
           ...
TT       6.915378
SLP      5.550500
SLP_     9.736124
Precp    0.000000
Class    0.000000
Length: 73, dtype: float64

# Delete Missing Values

In [10]:
df2 = df.dropna(axis=0)

In [11]:
df2

,WSR0,WSR1,WSR2,WSR3,WSR4,WSR5,WSR6,WSR7,WSR8,WSR9,...,RH50,U50,V50,HT50,KI,TT,SLP,SLP_,Precp,Class
0,0.8,1.8,2.4,2.1,2.0,2.1,1.5,1.7,1.9,2.3,...,0.15,10.67,-1.56,5795.0,-12.10,17.90,10330.0,-55.0,0.00,0
1,2.8,3.2,3.3,2.7,3.3,3.2,2.9,2.8,3.1,3.4,...,0.48,8.39,3.84,5805.0,14.05,29.00,10275.0,-55.0,0.00,0
2,2.9,2.8,2.6,2.1,2.2,2.5,2.5,2.7,2.2,2.5,...,0.60,6.94,9.80,5790.0,17.90,41.30,10235.0,-40.0,0.00,0
3,4.7,3.8,3.7,3.8,2.9,3.1,2.8,2.5,2.4,3.1,...,0.49,8.73,10.54,5775.0,31.15,51.70,10195.0,-40.0,2.08,0
6,3.7,3.2,3.8,5.1,6.0,7.0,6.3,6.4,6.3,5.4,...,0.84,6.86,25.60,5695.0,26.75,48.45,10040.0,-80.0,0.18,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1094,2.1,2.7,1.8,2.5,4.1,3.5,3.8,3.9,3.9,3.4,...,0.48,9.48,5.72,5745.0,-18.60,13.10,10270.0,40.0,3.63,0
1095,1.5,1.5,1.4,1.9,2.6,2.3,2.7,2.9,2.6,2.8,...,0.48,24.56,12.41,5710.0,15.20,41.50,10180.0,-90.0,0.00,0
1096,2.5,1.7,1.4,1.5,1.6,1.6,1.3,1.1,0.9,1.2,...,0.02,23.19,-9.94,5770.0,-20.70,31.70,10210.0,30.0,0.00,0
1097,3.0,3.0,3.1,4.6,2.4,1.7,2.4,3.0,3.2,3.6,...,0.56,18.23,3.95,5795.0,-29.50,16.90,10220.0,10.0,0.18,0
1098,0.8,0.8,0.9,0.8,1.2,1.0,1.7,1.7,1.5,2.6,...,0.04,22.46,8.17,5775.0,21.30,45.40,10170.0,-50.0,0.03,0

In [12]:
df2.describe()

,WSR0,WSR1,WSR2,WSR3,WSR4,WSR5,WSR6,WSR7,WSR8,WSR9,...,RH50,U50,V50,HT50,KI,TT,SLP,SLP_,Precp,Class
count,863.000000,863.000000,863.000000,863.000000,863.000000,863.000000,863.000000,863.000000,863.000000,863.000000,...,863.000000,863.000000,863.000000,863.000000,863.000000,863.000000,863.000000,863.000000,863.000000,863.000000
mean,1.722596,1.672885,1.629780,1.606489,1.600348,1.622711,1.720162,2.098957,2.581228,2.915991,...,0.279073,10.013986,0.232039,5819.971031,8.988007,36.985052,10165.283893,-1.181924,0.307173,0.045191
std,1.298665,1.305897,1.270788,1.250950,1.232652,1.223416,1.218282,1.213549,1.222534,1.228726,...,0.236734,10.157248,7.488925,81.207350,20.557655,11.296059,53.139874,34.542829,1.122714,0.207844
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.100000,0.100000,...,0.010000,-14.920000,-22.480000,5480.000000,-53.600000,-10.100000,9995.000000,-135.000000,0.000000,0.000000
25%,0.700000,0.600000,0.600000,0.600000,0.600000,0.700000,0.800000,1.200000,1.700000,2.100000,...,0.080000,2.045000,-4.025000,5770.000000,-5.100000,31.550000,10130.000000,-20.000000,0.000000,0.000000
50%,1.400000,1.400000,1.300000,1.300000,1.300000,1.400000,1.500000,1.900000,2.500000,2.900000,...,0.200000,9.360000,-0.320000,5830.000000,13.000000,40.500000,10160.000000,0.000000,0.000000,0.000000
75%,2.500000,2.500000,2.400000,2.300000,2.300000,2.200000,2.400000,2.900000,3.400000,3.700000,...,0.440000,17.570000,4.035000,5885.000000,26.175000,44.800000,10190.000000,15.000000,0.030000,0.000000
max,6.900000,6.900000,7.100000,6.700000,7.200000,7.400000,7.200000,7.500000,9.200000,8.300000,...,0.980000,41.360000,28.390000,5965.000000,42.050000,56.850000,10350.000000,140.000000,17.450000,1.000000

# Klasifikasi

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [14]:
x = df2.iloc[:, :-1].values
y = df2.iloc[:, -1].values

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=5)

In [16]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [17]:
classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[198   3]
 [ 14   1]]
0.9212962962962963

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [18]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[199   2]
 [ 14   1]]
0.9259259259259259

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [19]:
classifier = KNeighborsClassifier(n_neighbors=7, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[199   2]
 [ 14   1]]
0.9259259259259259

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [20]:
classifier = KNeighborsClassifier(n_neighbors=9, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[200   1]
 [ 15   0]]
0.9259259259259259

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)