In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("audit_5%.csv")

In [3]:
df

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,4.18,0.6,2.508,2.50,0.2,0.500,6.68,5.0,0.2,...,NaN,0.0,0.2,0.0,2.4,8.574,0.4,0.5,NaN,1
1,NaN,0.00,NaN,0.000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0
2,3.89,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096,0
3,3.89,0.00,0.2,NaN,10.80,0.6,6.480,NaN,6.0,0.6,...,0.4,0.0,0.2,NaN,4.4,17.530,0.4,0.5,3.5060,1
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.08,NaN,0.2,...,0.4,NaN,NaN,0.0,2.0,1.416,0.4,0.5,0.2832,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,2.37,0.39,0.2,0.078,0.14,0.2,0.028,0.53,5.0,0.2,...,0.4,0.0,0.2,NaN,2.0,1.622,0.4,0.5,0.3244,0
300,2.37,NaN,0.4,0.400,1.10,0.4,0.440,2.10,5.0,0.2,...,0.4,0.0,0.2,0.0,2.8,2.240,0.4,0.5,0.4480,0
301,2.37,0.42,0.2,0.084,0.27,0.2,NaN,0.69,5.0,NaN,...,0.4,0.0,0.2,0.0,2.0,1.538,0.4,0.5,0.3076,0
302,2.37,1.07,0.4,0.428,NaN,0.2,0.118,1.66,5.0,0.2,...,0.4,0.0,0.2,0.0,2.2,1.946,0.4,0.5,0.3892,0
303,2.37,1.29,0.4,0.516,0.25,NaN,0.050,NaN,5.0,0.2,...,0.4,0.0,0.2,0.0,2.2,1.966,0.4,0.5,0.3932,0

In [4]:
df.isnull().sum()

Sector_score      23
PARA_A            17
Score_A           21
Risk_A            25
PARA_B            15
Score_B           19
Risk_B            19
TOTAL             12
numbers           19
Score_B.1          9
Risk_C            21
Money_Value       17
Score_MV          17
Risk_D            11
District_Loss      5
PROB              17
RiSk_E            24
History           20
Prob              22
Risk_F            17
Score             16
Inherent_Risk     16
CONTROL_RISK      22
Detection_Risk    11
Audit_Risk        18
Risk               0
dtype: int64

In [5]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

Sector_score      7.565789
PARA_A            5.592105
Score_A           6.907895
Risk_A            8.223684
PARA_B            4.934211
Score_B           6.250000
Risk_B            6.250000
TOTAL             3.947368
numbers           6.250000
Score_B.1         2.960526
Risk_C            6.907895
Money_Value       5.592105
Score_MV          5.592105
Risk_D            3.618421
District_Loss     1.644737
PROB              5.592105
RiSk_E            7.894737
History           6.578947
Prob              7.236842
Risk_F            5.592105
Score             5.263158
Inherent_Risk     5.263158
CONTROL_RISK      7.236842
Detection_Risk    3.618421
Audit_Risk        5.921053
Risk              0.000000
dtype: float64

In [6]:
null_counts = df.isnull().sum().sum()
total = df.size
null_percentages = 100 * null_counts / total
print("total nilai :",total)
print("nilai hilang :",null_counts)
print("persentase hilang :",null_percentages)

total nilai : 7904
nilai hilang : 433
persentase hilang : 5.478238866396761

# Imputasi Mean

In [7]:
df2 = df.fillna(df.mean())

In [8]:
df2

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.890000,4.180000,0.600000,2.508000,2.500000,0.200000,0.500000,6.680000,5.000000,0.200000,...,0.5,0.000000,0.200000,0.000000,2.4,8.574,0.4,0.5,13.100316,1
1,3.294448,0.000000,0.438869,0.000000,4.830000,0.200000,0.966000,4.830000,5.000000,0.200000,...,0.4,0.000000,0.200000,0.000000,2.0,2.554,0.4,0.5,0.510800,0
2,3.890000,0.510000,0.200000,0.102000,0.230000,0.200000,0.046000,0.740000,5.000000,0.200000,...,0.4,0.000000,0.200000,0.000000,2.0,1.548,0.4,0.5,0.309600,0
3,3.890000,0.000000,0.200000,2.074824,10.800000,0.600000,6.480000,28.685616,6.000000,0.600000,...,0.4,0.000000,0.200000,0.115679,4.4,17.530,0.4,0.5,3.506000,1
4,3.890000,0.000000,0.200000,0.000000,0.080000,0.200000,0.016000,0.080000,5.136842,0.200000,...,0.4,0.221831,0.237589,0.000000,2.0,1.416,0.4,0.5,0.283200,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,2.370000,0.390000,0.200000,0.078000,0.140000,0.200000,0.028000,0.530000,5.000000,0.200000,...,0.4,0.000000,0.200000,0.115679,2.0,1.622,0.4,0.5,0.324400,0
300,2.370000,3.447491,0.400000,0.400000,1.100000,0.400000,0.440000,2.100000,5.000000,0.200000,...,0.4,0.000000,0.200000,0.000000,2.8,2.240,0.4,0.5,0.448000,0
301,2.370000,0.420000,0.200000,0.084000,0.270000,0.200000,15.144337,0.690000,5.000000,0.249492,...,0.4,0.000000,0.200000,0.000000,2.0,1.538,0.4,0.5,0.307600,0
302,2.370000,1.070000,0.400000,0.428000,25.121073,0.200000,0.118000,1.660000,5.000000,0.200000,...,0.4,0.000000,0.200000,0.000000,2.2,1.946,0.4,0.5,0.389200,0
303,2.370000,1.290000,0.400000,0.516000,0.250000,0.409123,0.050000,28.685616,5.000000,0.200000,...,0.4,0.000000,0.200000,0.000000,2.2,1.966,0.4,0.5,0.393200,0

In [9]:
df2.describe()

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
count,304.000000,304.000000,304.000000,304.000000,304.000000,304.000000,304.000000,304.000000,304.000000,304.000000,...,304.000000,304.000000,304.000000,304.000000,304.000000,304.000000,304.000000,304.0,304.000000,304.000000
mean,3.294448,3.447491,0.438869,2.074824,25.121073,0.409123,15.144337,28.685616,5.136842,0.249492,...,0.500000,0.221831,0.237589,0.115679,3.225000,34.343162,0.611348,0.5,13.100316,0.651316
std,0.536008,3.969922,0.166625,3.321535,76.756091,0.184697,46.177661,77.905487,0.357213,0.108354,...,0.243733,0.746885,0.094075,0.433572,0.942961,73.139190,0.495670,0.0,56.883192,0.477340
min,2.370000,0.000000,0.200000,0.000000,0.000000,0.200000,0.000000,0.000000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.000000,1.400000,0.400000,0.5,0.280000,0.000000
25%,2.720000,0.792500,0.200000,0.179000,0.342500,0.200000,0.084000,1.255000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.200000,2.227000,0.400000,0.5,0.447200,0.000000
50%,3.410000,2.220000,0.438869,1.332000,6.760000,0.409123,3.560000,9.585000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,3.225000,16.763000,0.400000,0.5,3.980000,1.000000
75%,3.890000,4.430000,0.600000,2.545500,32.845000,0.600000,19.198500,38.355000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,4.000000,41.984000,0.800000,0.5,13.100316,1.000000
max,3.890000,25.400000,0.600000,42.888000,1264.630000,0.600000,758.778000,1268.910000,9.000000,0.600000,...,2.400000,9.000000,0.600000,5.400000,5.200000,801.262000,5.800000,0.5,961.514400,1.000000

# Klasifikasi

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [11]:
x = df2.iloc[:, :-1].values
y = df2.iloc[:, -1].values

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=32)

In [13]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [14]:
classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[27  0]
 [ 2 47]]
0.9736842105263158