In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from scipy.spatial.distance import euclidean

In [2]:
df = pd.read_csv("transfusion_10%.csv")

In [3]:
df

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,2.0,50.0,NaN,98.0,1.0
1,0.0,13.0,3250.0,28.0,1.0
2,1.0,16.0,4000.0,NaN,1.0
3,2.0,20.0,5000.0,45.0,1.0
4,1.0,24.0,6000.0,77.0,0.0
...,...,...,...,...,...
743,23.0,2.0,500.0,NaN,0.0
744,NaN,2.0,NaN,52.0,0.0
745,NaN,NaN,NaN,62.0,0.0
746,39.0,1.0,250.0,NaN,0.0
747,72.0,NaN,250.0,72.0,0.0

In [4]:
df.dtypes

Recency (months)                              float64
Frequency (times)                             float64
Monetary (c.c. blood)                         float64
Time (months)                                 float64
whether he/she donated blood in March 2007    float64
dtype: object

In [5]:
df.isnull().sum()

Recency (months)                              107
Frequency (times)                              78
Monetary (c.c. blood)                          94
Time (months)                                  95
whether he/she donated blood in March 2007      0
dtype: int64

In [6]:
df.isnull().sum().sum()

374

In [7]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

Recency (months)                              14.304813
Frequency (times)                             10.427807
Monetary (c.c. blood)                         12.566845
Time (months)                                 12.700535
whether he/she donated blood in March 2007     0.000000
dtype: float64

In [8]:
null_counts = df.isnull().sum().sum()
total = df.size
null_percentages = 100 * null_counts / total
print("total nilai :",total)
print("nilai hilang :",null_counts)
print("persentase :",null_percentages)

total nilai : 3740
nilai hilang : 374
persentase : 10.0

In [9]:
def jarak(df2,col):
    euc_dist[col] = []
    euc_dist_append =euc_dist[col].append
    for row in range(df2.shape[0]):
        current = df2.index[df2.iloc[:,col] == 0].tolist()
        current = current[0]
        a = df2.iloc[current,col+1:].tolist()
        b = df2.iloc[current,:col].tolist()
        x1 = b+a
        if(row is not current):
            a=df2.iloc[row,col+1:].tolist()
            b=df2.iloc[row,:col].tolist()
            x2=b+a
        else:
            continue
        dist = euclidean(x1,x2)
        euc_dist_append([dist,df2.iloc[row,col]])
#         print(" x1 = ",x1,"\n x2 = ",x2,"\n distance = ",euc_dist[col])

    lst = list(euc_dist[col])
    lst.sort()
    euc_dist[col] = lst
#     print(euc_dist[col])

In [10]:
from collections import Counter

def hitung(val, k, temp=None, i=0, counter=0):
    counts = Counter(val)
    total_count = len(counts)
#     print("jumlah val:", total_count)
    if counter >= int((k/2)+1) and total_count <= 2 :
        print("median : ",int((k/2)+1))
        return temp
    elif i is not k:
        if temp is None:
            temp = val[i]
        elif temp != val[i]:
            temp = val[i]
            counter = 0
        # print(f"temp = {temp} , counter = {counter} , i = {i} , k = {k} , median = {int((k/2)+1)}, val[i] = {val[i]}")
        return hitung(val,k,temp,i+1,counter+1)
    else:
        return None    

def Final(df,col,k):
    terdekat = []
    mean = 0
    minimum = None
    maximum = None
    fuzzy_val = []
    euc_val = []
    terdekat_append = terdekat.append
    fuzzy_append = fuzzy_val.append
    
    for val in range(k):
        terdekat_append(euc_dist[col][val])
    
    for x,y in terdekat:
        if (minimum is None or maximum is None):
            minimum = y
            maximum = y
        elif(y<minimum):
            minimum = y
        elif(y>maximum):
            maximum = y
        mean += y
        euc_val.append(y)
    mean /= len(terdekat)
    euc_val.sort()
    print(euc_val)
    
    fuzzy = hitung(euc_val,5)
    print("min : ",minimum)
    print("max : ",maximum)
    print("mean : ",mean)
    for x,y in terdekat:
        if fuzzy is None:
            fuzzy_append((y,fuzzy_triangular(y,minimum,mean,maximum)))
        else:
            fuzzy_val.append((y,fuzzy))
        
    print("fuzzy : ",fuzzy_val)
    print("fuzzy : ",fuzzy)
    
    pembilang = 0
    penyebut = 0 
    
    for nilai,bobot in fuzzy_val:
        pembilang += nilai*bobot
        penyebut += bobot
            
    print("pembilang : ", pembilang)
    print("penyebut : ",penyebut)
    
    if fuzzy is not None:
        tertimbang = fuzzy
    else:
        tertimbang = pembilang / penyebut
    
    print("rata-rata tertimbang : ",tertimbang)
    index = dummy.index[dummy.iloc[:,col] == 0].tolist()
    index = index[0]
    
    if tertimbang == 0:
        tertimbang = dummy.iloc[index-1, col]
        
    dummy.iloc[index,col] = tertimbang
    print(" ")

In [11]:
def fuzzy_triangular(val, minimum, mean, maximum):
   if val <= minimum or val >= maximum: 
        return 0.0
   elif minimum < val <= mean:
        return float((val - minimum)/(mean - minimum)) 
   elif mean < val < maximum:
        return float((maximum - val)/(maximum - mean))

In [12]:
data = df.iloc[:, :-1]
df2 = df.copy()
dummy = df2.fillna(0)
dummy

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,2.0,50.0,0.0,98.0,1.0
1,0.0,13.0,3250.0,28.0,1.0
2,1.0,16.0,4000.0,0.0,1.0
3,2.0,20.0,5000.0,45.0,1.0
4,1.0,24.0,6000.0,77.0,0.0
...,...,...,...,...,...
743,23.0,2.0,500.0,0.0,0.0
744,0.0,2.0,0.0,52.0,0.0
745,0.0,0.0,0.0,62.0,0.0
746,39.0,1.0,250.0,0.0,0.0
747,72.0,0.0,250.0,72.0,0.0

In [13]:
count_zeros = np.count_nonzero(dummy == 0)

print("Jumlah angka 0 dalam dataset:", count_zeros)

Jumlah angka 0 dalam dataset: 949

In [14]:
euc_dist = {}

In [ ]:
for i in range(df2.shape[1]):
    print("Kolom :",i+1)
    current = dummy.index[dummy.iloc[:,i] == 0].tolist()
    for x in current:
        jarak(dummy,i)
        Final(dummy,i,5)
dummy

Kolom : 1
[1.0, 2.0, 2.0, 4.0, 14.0]
min :  1.0
max :  14.0
mean :  4.6
fuzzy :  [(2.0, 0.2777777777777778), (4.0, 0.8333333333333334), (1.0, 0.0), (2.0, 0.2777777777777778), (14.0, 0.0)]
fuzzy :  None
pembilang :  4.444444444444445
penyebut :  1.3888888888888888
rata-rata tertimbang :  3.2

[0.0, 4.0, 4.0, 9.0, 11.0]
min :  0.0
max :  11.0
mean :  5.6
fuzzy :  [(4.0, 0.7142857142857143), (0.0, 0.0), (4.0, 0.7142857142857143), (9.0, 0.37037037037037035), (11.0, 0.0)]
fuzzy :  None
pembilang :  9.047619047619047
penyebut :  1.798941798941799
rata-rata tertimbang :  5.029411764705882

[1.0, 5.0, 6.0, 11.0, 11.0]
min :  1.0
max :  11.0
mean :  6.8
fuzzy :  [(11.0, 0.0), (1.0, 0.0), (5.0, 0.6896551724137931), (6.0, 0.8620689655172414), (11.0, 0.0)]
fuzzy :  None
pembilang :  8.620689655172415
penyebut :  1.5517241379310347
rata-rata tertimbang :  5.555555555555555

[0.0, 2.0, 2.0, 2.0, 2.0]
median :  3
min :  0.0
max :  2.0
mean :  1.6
fuzzy :  [(2.0, 2.0), (2.0, 2.0), (0.0, 2.0), (2.0, 2.0), (2.0, 2.0)]
fuzzy :  2.0
pembilang :  16.0
penyebut :  10.0
rata-rata tertimbang :  2.0

[0.0, 1.0, 3.0, 4.0, 7.0]
min :  0.0
max :  7.0
mean :  3.0
fuzzy :  [(7.0, 0.0), (4.0, 0.75), (0.0, 0.0), (1.0, 0.3333333333333333), (3.0, 1.0)]
fuzzy :  None
pembilang :  6.333333333333334
penyebut :  2.083333333333333
rata-rata tertimbang :  3.040000000000001

[0.0, 0.0, 1.0, 11.0, 16.0]
min :  0.0
max :  16.0
mean :  5.6
fuzzy :  [(1.0, 0.17857142857142858), (0.0, 0.0), (16.0, 0.0), (0.0, 0.0), (11.0, 0.4807692307692307)]
fuzzy :  None
pembilang :  5.467032967032967
penyebut :  0.6593406593406593
rata-rata tertimbang :  8.291666666666668

[0.0, 1.0, 8.291666666666668, 11.0, 16.0]
min :  0.0
max :  16.0
mean :  7.258333333333335
fuzzy :  [(16.0, 0.0), (0.0, 0.0), (11.0, 0.5719733079122975), (1.0, 0.1377726750861079), (8.291666666666668, 0.8817921830314586)]
fuzzy :  None
pembilang :  13.741005913090559
penyebut :  1.591538166029864
rata-rata tertimbang :  8.633789755333282

[0.0, 2.0, 2.0, 2.0, 2.0]
median :  3
min :  0.0
max :  2.0
mean :  1.6
fuzzy :  [(2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (0.0, 2.0)]
fuzzy :  2.0
pembilang :  16.0
penyebut :  10.0
rata-rata tertimbang :  2.0

[1.0, 3.040000000000001, 7.0, 11.0, 20.0]
min :  1.0
max :  20.0
mean :  8.408
fuzzy :  [(1.0, 0.0), (3.040000000000001, 0.27537796976241913), (7.0, 0.8099352051835854), (20.0, 0.0), (11.0, 0.7763975155279502)]
fuzzy :  None
pembilang :  15.047068135170305
penyebut :  1.8617106904739549
rata-rata tertimbang :  8.082387995172127

[4.0, 4.0, 5.029411764705882, 9.0, 11.0]
min :  4.0
max :  11.0
mean :  6.605882352941177
fuzzy :  [(4.0, 0.0), (4.0, 0.0), (5.029411764705882, 0.3950338600451466), (9.0, 0.4551539491298528), (11.0, 0.0)]
fuzzy :  None
pembilang :  6.083173485336912
penyebut :  0.8501878091749995
rata-rata tertimbang :  7.1550937565664094

[2.0, 2.0, 4.0, 4.0, 14.0]
min :  2.0
max :  14.0
mean :  5.2
fuzzy :  [(14.0, 0.0), (2.0, 0.0), (2.0, 0.0), (4.0, 0.625), (4.0, 0.625)]
fuzzy :  None
pembilang :  5.0
penyebut :  1.25
rata-rata tertimbang :  4.0

[0.0, 2.0, 2.0, 4.0, 14.0]
min :  0.0
max :  14.0
mean :  4.4
fuzzy :  [(0.0, 0.0), (14.0, 0.0), (2.0, 0.45454545454545453), (4.0, 0.9090909090909091), (2.0, 0.45454545454545453)]
fuzzy :  None
pembilang :  5.454545454545454
penyebut :  1.8181818181818181
rata-rata tertimbang :  3.0

[0.0, 2.0, 2.0, 2.0, 2.0]
median :  3
min :  0.0
max :  2.0
mean :  1.6
fuzzy :  [(2.0, 2.0), (0.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0)]
fuzzy :  2.0
pembilang :  16.0
penyebut :  10.0
rata-rata tertimbang :  2.0

[2.0, 2.0, 2.0, 2.0, 4.0]
median :  3
min :  2.0
max :  4.0
mean :  2.4
fuzzy :  [(2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (4.0, 2.0)]
fuzzy :  2.0
pembilang :  24.0
penyebut :  10.0
rata-rata tertimbang :  2.0

[4.0, 4.0, 9.0, 9.0, 12.0]
min :  4.0
max :  12.0
mean :  7.6
fuzzy :  [(4.0, 0.0), (9.0, 0.6818181818181818), (4.0, 0.0), (9.0, 0.6818181818181818), (12.0, 0.0)]
fuzzy :  None
pembilang :  12.272727272727272
penyebut :  1.3636363636363635
rata-rata tertimbang :  9.0

[4.0, 4.0, 5.029411764705882, 7.1550937565664094, 9.0]
min :  4.0
max :  9.0
mean :  5.8369011042544585
fuzzy :  [(9.0, 0.0), (5.029411764705882, 0.5604067428135652), (4.0, 0.0), (7.1550937565664094, 0.5832591089437773), (4.0, 0.0)]
fuzzy :  None
pembilang :  6.991789874191157
penyebut :  1.1436658517573424
rata-rata tertimbang :  6.113490110286725

[0.0, 2.0, 2.0, 2.0, 11.0]
min :  0.0
max :  11.0
mean :  3.4
fuzzy :  [(2.0, 0.5882352941176471), (11.0, 0.0), (0.0, 0.0), (2.0, 0.5882352941176471), (2.0, 0.5882352941176471)]
fuzzy :  None
pembilang :  3.5294117647058822
penyebut :  1.7647058823529411
rata-rata tertimbang :  2.0

[0.0, 3.0, 8.0, 14.0, 23.0]
min :  0.0
max :  23.0
mean :  9.6
fuzzy :  [(23.0, 0.0), (0.0, 0.0), (8.0, 0.8333333333333334), (3.0, 0.3125), (14.0, 0.6716417910447761)]
fuzzy :  None
pembilang :  17.007151741293534
penyebut :  1.8174751243781095
rata-rata tertimbang :  9.357570573139435

[2.0, 3.0, 4.0, 14.0, 16.0]
min :  2.0
max :  16.0
mean :  7.8
fuzzy :  [(2.0, 0.0), (3.0, 0.1724137931034483), (14.0, 0.24390243902439027), (4.0, 0.3448275862068966), (16.0, 0.0)]
fuzzy :  None
pembilang :  5.311185870479395
penyebut :  0.7611438183347351
rata-rata tertimbang :  6.977900552486188

[0.0, 0.0, 11.0, 11.0, 11.0]
median :  3
min :  0.0
max :  11.0
mean :  6.6
fuzzy :  [(0.0, 11.0), (0.0, 11.0), (11.0, 11.0), (11.0, 11.0), (11.0, 11.0)]
fuzzy :  11.0
pembilang :  363.0
penyebut :  55.0
rata-rata tertimbang :  11.0

[0.0, 2.0, 2.0, 3.0, 4.0]
min :  0.0
max :  4.0
mean :  2.2
fuzzy :  [(0.0, 0.0), (2.0, 0.9090909090909091), (2.0, 0.9090909090909091), (3.0, 0.5555555555555556), (4.0, 0.0)]
fuzzy :  None
pembilang :  5.303030303030303
penyebut :  2.3737373737373737
rata-rata tertimbang :  2.234042553191489

[4.0, 4.0, 11.0, 11.0, 13.0]
min :  4.0
max :  13.0
mean :  8.6
fuzzy :  [(4.0, 0.0), (4.0, 0.0), (11.0, 0.45454545454545453), (11.0, 0.45454545454545453), (13.0, 0.0)]
fuzzy :  None
pembilang :  10.0
penyebut :  0.9090909090909091
rata-rata tertimbang :  11.0

[4.0, 11.0, 11.0, 11.0, 13.0]
min :  4.0
max :  13.0
mean :  10.0
fuzzy :  [(11.0, 0.6666666666666666), (11.0, 0.6666666666666666), (13.0, 0.0), (4.0, 0.0), (11.0, 0.6666666666666666)]
fuzzy :  None
pembilang :  22.0
penyebut :  2.0
rata-rata tertimbang :  11.0

[0.0, 2.0, 2.0, 2.0, 2.0]
median :  3
min :  0.0
max :  2.0
mean :  1.6
fuzzy :  [(0.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0)]
fuzzy :  2.0
pembilang :  16.0
penyebut :  10.0
rata-rata tertimbang :  2.0

[2.0, 4.0, 4.0, 4.0, 11.0]
min :  2.0
max :  11.0
mean :  5.0
fuzzy :  [(2.0, 0.0), (11.0, 0.0), (4.0, 0.6666666666666666), (4.0, 0.6666666666666666), (4.0, 0.6666666666666666)]
fuzzy :  None
pembilang :  8.0
penyebut :  2.0
rata-rata tertimbang :  4.0

[2.0, 2.0, 2.0, 2.0, 4.0]
median :  3
min :  2.0
max :  4.0
mean :  2.4
fuzzy :  [(2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (4.0, 2.0), (2.0, 2.0)]
fuzzy :  2.0
pembilang :  24.0
penyebut :  10.0
rata-rata tertimbang :  2.0

[0.0, 2.0, 11.0, 14.0, 16.0]
min :  0.0
max :  16.0
mean :  8.6
fuzzy :  [(2.0, 0.23255813953488372), (11.0, 0.6756756756756757), (0.0, 0.0), (16.0, 0.0), (14.0, 0.27027027027027023)]
fuzzy :  None
pembilang :  11.681332495285982
penyebut :  1.1785040854808295
rata-rata tertimbang :  9.912

[2.0, 2.0, 3.0, 4.0, 14.0]
min :  2.0
max :  14.0
mean :  5.0
fuzzy :  [(14.0, 0.0), (3.0, 0.3333333333333333), (2.0, 0.0), (4.0, 0.6666666666666666), (2.0, 0.0)]
fuzzy :  None
pembilang :  3.6666666666666665
penyebut :  1.0
rata-rata tertimbang :  3.6666666666666665

[0.0, 2.0, 4.0, 4.0, 11.0]
min :  0.0
max :  11.0
mean :  4.2
fuzzy :  [(4.0, 0.9523809523809523), (0.0, 0.0), (4.0, 0.9523809523809523), (2.0, 0.47619047619047616), (11.0, 0.0)]
fuzzy :  None
pembilang :  8.571428571428571
penyebut :  2.380952380952381
rata-rata tertimbang :  3.6

[0.0, 0.0, 0.0, 4.0, 4.0]
median :  3
min :  0.0
max :  4.0
mean :  1.6
fuzzy :  [(0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (4.0, 0.0), (4.0, 0.0)]
fuzzy :  0.0
pembilang :  0.0
penyebut :  0.0
rata-rata tertimbang :  0.0

[0.0, 2.0, 2.0, 2.0, 2.0]
median :  3
min :  0.0
max :  2.0
mean :  1.6
fuzzy :  [(2.0, 2.0), (0.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0)]
fuzzy :  2.0
pembilang :  16.0
penyebut :  10.0
rata-rata tertimbang :  2.0

[0.0, 0.0, 4.0, 4.0, 4.0]
median :  3
min :  0.0
max :  4.0
mean :  2.4
fuzzy :  [(0.0, 4.0), (0.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0)]
fuzzy :  4.0
pembilang :  48.0
penyebut :  20.0
rata-rata tertimbang :  4.0

[0.0, 4.0, 4.0, 4.0, 4.0]
median :  3
min :  0.0
max :  4.0
mean :  3.2
fuzzy :  [(0.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0)]
fuzzy :  4.0
pembilang :  64.0
penyebut :  20.0
rata-rata tertimbang :  4.0

[0.0, 2.0, 4.0, 4.0, 11.0]
min :  0.0
max :  11.0
mean :  4.2
fuzzy :  [(4.0, 0.9523809523809523), (11.0, 0.0), (2.0, 0.47619047619047616), (4.0, 0.9523809523809523), (0.0, 0.0)]
fuzzy :  None
pembilang :  8.571428571428571
penyebut :  2.3809523809523805
rata-rata tertimbang :  3.6000000000000005

[0.0, 0.0, 11.0, 14.0, 14.0]
min :  0.0
max :  14.0
mean :  7.8
fuzzy :  [(11.0, 0.48387096774193544), (14.0, 0.0), (14.0, 0.0), (0.0, 0.0), (0.0, 0.0)]
fuzzy :  None
pembilang :  5.32258064516129
penyebut :  0.48387096774193544
rata-rata tertimbang :  11.0

[2.0, 2.0, 2.0, 2.0, 4.0]
median :  3
min :  2.0
max :  4.0
mean :  2.4
fuzzy :  [(4.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0)]
fuzzy :  2.0
pembilang :  24.0
penyebut :  10.0
rata-rata tertimbang :  2.0

[2.0, 2.0, 2.0, 11.0, 11.0]
median :  3
min :  2.0
max :  11.0
mean :  5.6
fuzzy :  [(2.0, 2.0), (11.0, 2.0), (11.0, 2.0), (2.0, 2.0), (2.0, 2.0)]
fuzzy :  2.0
pembilang :  56.0
penyebut :  10.0
rata-rata tertimbang :  2.0

[0.0, 0.0, 6.0, 11.0, 23.0]
min :  0.0
max :  23.0
mean :  8.0
fuzzy :  [(0.0, 0.0), (11.0, 0.8), (23.0, 0.0), (0.0, 0.0), (6.0, 0.75)]
fuzzy :  None
pembilang :  13.3
penyebut :  1.55
rata-rata tertimbang :  8.580645161290322

[0.0, 2.0, 8.633789755333282, 11.0, 16.0]
min :  0.0
max :  16.0
mean :  7.5267579510666565
fuzzy :  [(0.0, 0.0), (11.0, 0.5900929031797725), (16.0, 0.0), (8.633789755333282, 0.869349677741593), (2.0, 0.2657186550972547)]
fuzzy :  None
pembilang :  14.52824158665966
penyebut :  1.7251612360186201
rata-rata tertimbang :  8.421381887868279

[0.0, 11.0, 14.0, 14.0, 14.0]
min :  0.0
max :  14.0
mean :  10.6
fuzzy :  [(0.0, 0.0), (14.0, 0.0), (14.0, 0.0), (11.0, 0.8823529411764705), (14.0, 0.0)]
fuzzy :  None
pembilang :  9.705882352941176
penyebut :  0.8823529411764705
rata-rata tertimbang :  11.0

[0.0, 2.0, 18.0, 21.0, 23.0]
min :  0.0
max :  23.0
mean :  12.8
fuzzy :  [(0.0, 0.0), (2.0, 0.15625), (18.0, 0.4901960784313726), (21.0, 0.19607843137254904), (23.0, 0.0)]
fuzzy :  None
pembilang :  13.253676470588236
penyebut :  0.8425245098039216
rata-rata tertimbang :  15.73090909090909

[0.0, 9.0, 11.0, 11.0, 14.0]
min :  0.0
max :  14.0
mean :  9.0
fuzzy :  [(0.0, 0.0), (11.0, 0.6), (9.0, 1.0), (14.0, 0.0), (11.0, 0.6)]
fuzzy :  None
pembilang :  22.2
penyebut :  2.2
rata-rata tertimbang :  10.09090909090909

[0.0, 0.0, 4.0, 4.0, 4.0]
median :  3
min :  0.0
max :  4.0
mean :  2.4
fuzzy :  [(0.0, 4.0), (0.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0)]
fuzzy :  4.0
pembilang :  48.0
penyebut :  20.0
rata-rata tertimbang :  4.0

In [ ]:
dummy.describe()

# Klasifikasi

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [ ]:
x = dummy.values
y = df.iloc[:, -1].values

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=94)

In [ ]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)