In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from scipy.spatial.distance import euclidean

In [2]:
df = pd.read_csv("transfusion_10%.csv")

In [3]:
df

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,2.0,50.0,NaN,98.0,1.0
1,0.0,13.0,3250.0,28.0,1.0
2,1.0,16.0,4000.0,NaN,1.0
3,2.0,20.0,5000.0,45.0,1.0
4,1.0,24.0,6000.0,77.0,0.0
...,...,...,...,...,...
743,23.0,2.0,500.0,NaN,0.0
744,NaN,2.0,NaN,52.0,0.0
745,NaN,NaN,NaN,62.0,0.0
746,39.0,1.0,250.0,NaN,0.0
747,72.0,NaN,250.0,72.0,0.0

In [4]:
df.dtypes

Recency (months)                              float64
Frequency (times)                             float64
Monetary (c.c. blood)                         float64
Time (months)                                 float64
whether he/she donated blood in March 2007    float64
dtype: object

In [5]:
df.isnull().sum()

Recency (months)                              107
Frequency (times)                              78
Monetary (c.c. blood)                          94
Time (months)                                  95
whether he/she donated blood in March 2007      0
dtype: int64

In [6]:
df.isnull().sum().sum()

374

In [7]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

Recency (months)                              14.304813
Frequency (times)                             10.427807
Monetary (c.c. blood)                         12.566845
Time (months)                                 12.700535
whether he/she donated blood in March 2007     0.000000
dtype: float64

In [8]:
null_counts = df.isnull().sum().sum()
total = df.size
null_percentages = 100 * null_counts / total
print("total nilai :",total)
print("nilai hilang :",null_counts)
print("persentase :",null_percentages)

total nilai : 3740
nilai hilang : 374
persentase : 10.0

In [9]:
def jarak(df2,col):
    euc_dist[col] = []
    euc_dist_append =euc_dist[col].append
    for row in range(df2.shape[0]):
        current = df2.index[df2.iloc[:,col] == 0].tolist()
        current = current[0]
        a = df2.iloc[current,col+1:].tolist()
        b = df2.iloc[current,:col].tolist()
        x1 = b+a
        if(row is not current):
            a=df2.iloc[row,col+1:].tolist()
            b=df2.iloc[row,:col].tolist()
            x2=b+a
        else:
            continue
        dist = euclidean(x1,x2)
        euc_dist_append([dist,df2.iloc[row,col]])
#         print(" x1 = ",x1,"\n x2 = ",x2,"\n distance = ",euc_dist[col])

    lst = list(euc_dist[col])
    lst.sort()
    euc_dist[col] = lst
#     print(euc_dist[col])

In [10]:
from collections import Counter

def hitung(val, k, temp=None, i=0, counter=0):
    counts = Counter(val)
    total_count = len(counts)
#     print("jumlah val:", total_count)
    if counter >= int((k/2)+1) and total_count <= 2 :
        print("median : ",int((k/2)+1))
        return temp
    elif i is not k:
        if temp is None:
            temp = val[i]
        elif temp != val[i]:
            temp = val[i]
            counter = 0
        # print(f"temp = {temp} , counter = {counter} , i = {i} , k = {k} , median = {int((k/2)+1)}, val[i] = {val[i]}")
        return hitung(val,k,temp,i+1,counter+1)
    else:
        return None    

def Final(df,col,k):
    terdekat = []
    mean = 0
    minimum = None
    maximum = None
    fuzzy_val = []
    euc_val = []
    terdekat_append = terdekat.append
    fuzzy_append = fuzzy_val.append
    
    for val in range(k):
        terdekat_append(euc_dist[col][val])
    
    for x,y in terdekat:
        if (minimum is None or maximum is None):
            minimum = y
            maximum = y
        elif(y<minimum):
            minimum = y
        elif(y>maximum):
            maximum = y
        mean += y
        euc_val.append(y)
    mean /= len(terdekat)
    euc_val.sort()
    print(euc_val)
    
    fuzzy = hitung(euc_val,9)
    print("min : ",minimum)
    print("max : ",maximum)
    print("mean : ",mean)
    for x,y in terdekat:
        if fuzzy is None:
            fuzzy_append((y,fuzzy_triangular(y,minimum,mean,maximum)))
        else:
            fuzzy_val.append((y,fuzzy))
        
    print("fuzzy : ",fuzzy_val)
    print("fuzzy : ",fuzzy)
    
    pembilang = 0
    penyebut = 0 
    
    for nilai,bobot in fuzzy_val:
        pembilang += nilai*bobot
        penyebut += bobot
            
    print("pembilang : ", pembilang)
    print("penyebut : ",penyebut)
    
    if fuzzy is not None:
        tertimbang = fuzzy
    else:
        tertimbang = pembilang / penyebut
    
    print("rata-rata tertimbang : ",tertimbang)
    index = dummy.index[dummy.iloc[:,col] == 0].tolist()
    index = index[0]
    
    if tertimbang == 0:
        tertimbang = dummy.iloc[index-1, col]
    
    dummy.iloc[index,col] = tertimbang
    print(" ")

In [11]:
def fuzzy_triangular(val, minimum, mean, maximum):
   if val <= minimum or val >= maximum: 
        return 0.0
   elif minimum < val <= mean:
        return float((val - minimum)/(mean - minimum)) 
   elif mean < val < maximum:
        return float((maximum - val)/(maximum - mean))

In [12]:
data = df.iloc[:, :-1]
df2 = df.copy()
dummy = df2.fillna(0)
dummy

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,2.0,50.0,0.0,98.0,1.0
1,0.0,13.0,3250.0,28.0,1.0
2,1.0,16.0,4000.0,0.0,1.0
3,2.0,20.0,5000.0,45.0,1.0
4,1.0,24.0,6000.0,77.0,0.0
...,...,...,...,...,...
743,23.0,2.0,500.0,0.0,0.0
744,0.0,2.0,0.0,52.0,0.0
745,0.0,0.0,0.0,62.0,0.0
746,39.0,1.0,250.0,0.0,0.0
747,72.0,0.0,250.0,72.0,0.0

In [13]:
euc_dist = {}

In [ ]:
for i in range(df2.shape[1]):
    print("Kolom :",i+1)
    current = dummy.index[dummy.iloc[:,i] == 0].tolist()
    for x in current:
        jarak(dummy,i)
        Final(dummy,i,9)
dummy

Kolom : 1
[0.0, 1.0, 2.0, 2.0, 2.0, 4.0, 12.0, 14.0, 21.0]
min :  0.0
max :  21.0
mean :  6.444444444444445
fuzzy :  [(2.0, 0.3103448275862069), (4.0, 0.6206896551724138), (1.0, 0.15517241379310345), (2.0, 0.3103448275862069), (14.0, 0.48091603053435117), (21.0, 0.0), (12.0, 0.6183206106870229), (2.0, 0.3103448275862069), (0.0, 0.0)]
fuzzy :  None
pembilang :  18.65267175572519
penyebut :  2.806133192945512
rata-rata tertimbang :  6.647108484592655

[0.0, 2.0, 4.0, 4.0, 4.0, 9.0, 9.0, 11.0, 11.0]
min :  0.0
max :  11.0
mean :  6.0
fuzzy :  [(4.0, 0.6666666666666666), (0.0, 0.0), (4.0, 0.6666666666666666), (9.0, 0.4), (11.0, 0.0), (9.0, 0.4), (11.0, 0.0), (2.0, 0.3333333333333333), (4.0, 0.6666666666666666)]
fuzzy :  None
pembilang :  15.866666666666665
penyebut :  3.1333333333333333
rata-rata tertimbang :  5.0638297872340425

[1.0, 2.0, 2.0, 3.0, 4.0, 5.0, 6.0, 11.0, 11.0]
min :  1.0
max :  11.0
mean :  5.0
fuzzy :  [(11.0, 0.0), (1.0, 0.0), (5.0, 1.0), (6.0, 0.8333333333333334), (11.0, 0.0), (2.0, 0.25), (3.0, 0.5), (4.0, 0.75), (2.0, 0.25)]
fuzzy :  None
pembilang :  15.5
penyebut :  3.5833333333333335
rata-rata tertimbang :  4.325581395348837

[0.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 11.0]
min :  0.0
max :  11.0
mean :  2.7777777777777777
fuzzy :  [(2.0, 0.72), (2.0, 0.72), (0.0, 0.0), (2.0, 0.72), (2.0, 0.72), (2.0, 0.72), (11.0, 0.0), (2.0, 0.72), (2.0, 0.72)]
fuzzy :  None
pembilang :  10.079999999999998
penyebut :  5.039999999999999
rata-rata tertimbang :  2.0

[0.0, 1.0, 3.0, 4.0, 4.0, 7.0, 11.0, 16.0, 20.0]
min :  0.0
max :  20.0
mean :  7.333333333333333
fuzzy :  [(7.0, 0.9545454545454546), (4.0, 0.5454545454545455), (0.0, 0.0), (1.0, 0.13636363636363638), (3.0, 0.4090909090909091), (20.0, 0.0), (11.0, 0.7105263157894737), (16.0, 0.3157894736842105), (4.0, 0.5454545454545455)]
fuzzy :  None
pembilang :  25.277511961722492
penyebut :  3.6172248803827753
rata-rata tertimbang :  6.988095238095239

[0.0, 0.0, 0.0, 1.0, 2.0, 2.0, 2.0, 11.0, 16.0]
min :  0.0
max :  16.0
mean :  3.7777777777777777
fuzzy :  [(1.0, 0.2647058823529412), (0.0, 0.0), (16.0, 0.0), (0.0, 0.0), (11.0, 0.4090909090909091), (2.0, 0.5294117647058824), (2.0, 0.5294117647058824), (2.0, 0.5294117647058824), (0.0, 0.0)]
fuzzy :  None
pembilang :  7.941176470588235
penyebut :  2.262032085561497
rata-rata tertimbang :  3.5106382978723407

[0.0, 0.0, 1.0, 2.0, 2.0, 3.5106382978723407, 4.0, 11.0, 16.0]
min :  0.0
max :  16.0
mean :  4.390070921985815
fuzzy :  [(16.0, 0.0), (0.0, 0.0), (11.0, 0.4306658521686011), (1.0, 0.22778675282714056), (3.5106382978723407, 0.7996768982229403), (2.0, 0.4555735056542811), (2.0, 0.4555735056542811), (0.0, 0.0), (4.0, 0.9111470113085622)]
fuzzy :  None
pembilang :  13.239369539358343
penyebut :  3.2804235258358063
rata-rata tertimbang :  4.035872025391946

[0.0, 0.0, 0.0, 2.0, 2.0, 2.0, 2.0, 4.0, 4.0]
min :  0.0
max :  4.0
mean :  1.7777777777777777
fuzzy :  [(2.0, 0.8999999999999999), (2.0, 0.8999999999999999), (2.0, 0.8999999999999999), (2.0, 0.8999999999999999), (0.0, 0.0), (4.0, 0.0), (0.0, 0.0), (4.0, 0.0), (0.0, 0.0)]
fuzzy :  None
pembilang :  7.199999999999999
penyebut :  3.5999999999999996
rata-rata tertimbang :  2.0

[1.0, 3.0, 4.0, 4.0, 6.988095238095239, 7.0, 11.0, 16.0, 20.0]
min :  1.0
max :  20.0
mean :  8.10978835978836
fuzzy :  [(1.0, 0.0), (6.988095238095239, 0.8422325581395349), (7.0, 0.8439069767441859), (20.0, 0.0), (11.0, 0.7569251307153188), (4.0, 0.42195348837209296), (3.0, 0.2813023255813953), (16.0, 0.33641116920680836), (4.0, 0.42195348837209296)]
fuzzy :  None
pembilang :  29.72124019501133
penyebut :  3.904685137131429
rata-rata tertimbang :  7.611686768896811

[2.0, 4.0, 4.0, 4.0, 5.0638297872340425, 9.0, 9.0, 11.0, 11.0]
min :  2.0
max :  11.0
mean :  6.5626477541371155
fuzzy :  [(4.0, 0.4383419689119171), (4.0, 0.4383419689119171), (5.0638297872340425, 0.6715025906735752), (9.0, 0.4507192328183271), (11.0, 0.0), (11.0, 0.0), (4.0, 0.4383419689119171), (9.0, 0.4507192328183271), (2.0, 0.0)]
fuzzy :  None
pembilang :  16.77342463853057
penyebut :  2.8879669630459808
rata-rata tertimbang :  5.8080389606809755

[0.0, 2.0, 2.0, 2.0, 2.0, 4.0, 4.0, 4.0, 14.0]
min :  0.0
max :  14.0
mean :  3.7777777777777777
fuzzy :  [(14.0, 0.0), (2.0, 0.5294117647058824), (2.0, 0.5294117647058824), (4.0, 0.9782608695652175), (4.0, 0.9782608695652175), (2.0, 0.5294117647058824), (2.0, 0.5294117647058824), (4.0, 0.9782608695652175), (0.0, 0.0)]
fuzzy :  None
pembilang :  15.97442455242967
penyebut :  5.052429667519182
rata-rata tertimbang :  3.1617312072892942

[0.0, 0.0, 0.0, 2.0, 2.0, 4.0, 4.0, 11.0, 14.0]
min :  0.0
max :  14.0
mean :  4.111111111111111
fuzzy :  [(0.0, 0.0), (14.0, 0.0), (2.0, 0.4864864864864865), (4.0, 0.972972972972973), (2.0, 0.4864864864864865), (0.0, 0.0), (4.0, 0.972972972972973), (0.0, 0.0), (11.0, 0.3033707865168539)]
fuzzy :  None
pembilang :  13.066808381415122
penyebut :  3.2222897054357733
rata-rata tertimbang :  4.055131467345207

[0.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 4.0, 11.0]
min :  0.0
max :  11.0
mean :  3.0
fuzzy :  [(2.0, 0.6666666666666666), (0.0, 0.0), (2.0, 0.6666666666666666), (2.0, 0.6666666666666666), (2.0, 0.6666666666666666), (11.0, 0.0), (2.0, 0.6666666666666666), (2.0, 0.6666666666666666), (4.0, 0.875)]
fuzzy :  None
pembilang :  11.5
penyebut :  4.875
rata-rata tertimbang :  2.358974358974359

[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 4.0, 4.0]
median :  5
min :  2.0
max :  4.0
mean :  2.4444444444444446
fuzzy :  [(2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (4.0, 2.0), (4.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0)]
fuzzy :  2.0
pembilang :  44.0
penyebut :  18.0
rata-rata tertimbang :  2.0

[4.0, 4.0, 4.0, 4.0, 8.0, 8.0, 9.0, 9.0, 12.0]
min :  4.0
max :  12.0
mean :  6.888888888888889
fuzzy :  [(4.0, 0.0), (9.0, 0.5869565217391305), (4.0, 0.0), (9.0, 0.5869565217391305), (12.0, 0.0), (4.0, 0.0), (4.0, 0.0), (8.0, 0.782608695652174), (8.0, 0.782608695652174)]
fuzzy :  None
pembilang :  23.086956521739133
penyebut :  2.739130434782609
rata-rata tertimbang :  8.428571428571429

[2.0, 4.0, 4.0, 5.0638297872340425, 5.8080389606809755, 9.0, 9.0, 11.0, 11.0]
min :  2.0
max :  11.0
mean :  6.763540971990557
fuzzy :  [(9.0, 0.4720923740267416), (5.0638297872340425, 0.6431832549041243), (4.0, 0.41985573584019226), (5.8080389606809755, 0.799413499972416), (4.0, 0.41985573584019226), (11.0, 0.0), (2.0, 0.0), (9.0, 0.4720923740267416), (11.0, 0.0)]
fuzzy :  None
pembilang :  19.75650389757067
penyebut :  3.226492974610408
rata-rata tertimbang :  6.12321305300726

[0.0, 2.0, 2.0, 2.0, 2.0, 2.0, 4.0, 4.0, 11.0]
min :  0.0
max :  11.0
mean :  3.2222222222222223
fuzzy :  [(2.0, 0.6206896551724138), (11.0, 0.0), (0.0, 0.0), (2.0, 0.6206896551724138), (2.0, 0.6206896551724138), (2.0, 0.6206896551724138), (4.0, 0.9), (2.0, 0.6206896551724138), (4.0, 0.9)]
fuzzy :  None
pembilang :  13.406896551724138
penyebut :  4.903448275862069
rata-rata tertimbang :  2.7341772151898733

[0.0, 0.0, 3.0, 8.0, 11.0, 11.0, 14.0, 23.0, 23.0]
min :  0.0
max :  23.0
mean :  10.333333333333334
fuzzy :  [(23.0, 0.0), (0.0, 0.0), (8.0, 0.7741935483870968), (3.0, 0.29032258064516125), (14.0, 0.7105263157894737), (23.0, 0.0), (11.0, 0.9473684210526316), (0.0, 0.0), (11.0, 0.9473684210526316)]
fuzzy :  None
pembilang :  37.85398981324279
penyebut :  3.669779286926995
rata-rata tertimbang :  10.315058986814712

[2.0, 2.0, 2.0, 2.0, 3.0, 4.0, 4.0, 14.0, 16.0]
min :  2.0
max :  16.0
mean :  5.444444444444445
fuzzy :  [(2.0, 0.0), (3.0, 0.29032258064516125), (14.0, 0.18947368421052632), (4.0, 0.5806451612903225), (16.0, 0.0), (4.0, 0.5806451612903225), (2.0, 0.0), (2.0, 0.0), (2.0, 0.0)]
fuzzy :  None
pembilang :  8.168760611205432
penyebut :  1.6410865874363325
rata-rata tertimbang :  4.977653631284916

[0.0, 0.0, 2.0, 2.0, 11.0, 11.0, 11.0, 11.0, 23.0]
min :  0.0
max :  23.0
mean :  7.888888888888889
fuzzy :  [(0.0, 0.0), (0.0, 0.0), (11.0, 0.7941176470588236), (11.0, 0.7941176470588236), (11.0, 0.7941176470588236), (23.0, 0.0), (2.0, 0.2535211267605634), (2.0, 0.2535211267605634), (11.0, 0.7941176470588236)]
fuzzy :  None
pembilang :  35.955260977630495
penyebut :  3.6835128417564214
rata-rata tertimbang :  9.761133603238866

[0.0, 2.0, 2.0, 3.0, 4.0, 4.0, 4.0, 14.0, 14.0]
min :  0.0
max :  14.0
mean :  5.222222222222222
fuzzy :  [(0.0, 0.0), (2.0, 0.3829787234042553), (2.0, 0.3829787234042553), (3.0, 0.5744680851063829), (4.0, 0.7659574468085106), (4.0, 0.7659574468085106), (4.0, 0.7659574468085106), (14.0, 0.0), (14.0, 0.0)]
fuzzy :  None
pembilang :  12.446808510638299
penyebut :  3.6382978723404253
rata-rata tertimbang :  3.421052631578948

[0.0, 2.0, 2.0, 4.0, 4.0, 11.0, 11.0, 13.0, 16.0]
min :  0.0
max :  16.0
mean :  7.0
fuzzy :  [(4.0, 0.5714285714285714), (4.0, 0.5714285714285714), (11.0, 0.5555555555555556), (11.0, 0.5555555555555556), (13.0, 0.3333333333333333), (2.0, 0.2857142857142857), (0.0, 0.0), (16.0, 0.0), (2.0, 0.2857142857142857)]
fuzzy :  None
pembilang :  22.269841269841272
penyebut :  3.1587301587301586
rata-rata tertimbang :  7.050251256281408

[2.0, 2.0, 4.0, 4.0, 7.050251256281408, 11.0, 11.0, 13.0, 16.0]
min :  2.0
max :  16.0
mean :  7.783361250697933
fuzzy :  [(11.0, 0.6085213373199237), (11.0, 0.6085213373199237), (13.0, 0.36511280239195426), (4.0, 0.34581965630430594), (7.050251256281408, 0.8732380768488128), (4.0, 0.34581965630430594), (2.0, 0.0), (16.0, 0.0), (2.0, 0.0)]
fuzzy :  None
pembilang :  27.057040950904277
penyebut :  3.147032866489227
rata-rata tertimbang :  8.597635327872704

[0.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
median :  5
min :  0.0
max :  2.0
mean :  1.7777777777777777
fuzzy :  [(0.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0), (2.0, 2.0)]
fuzzy :  2.0
pembilang :  32.0
penyebut :  18.0
rata-rata tertimbang :  2.0

[0.0, 2.0, 2.0, 4.0, 4.0, 4.0, 4.0, 4.0, 11.0]
min :  0.0
max :  11.0
mean :  3.888888888888889
fuzzy :  [(2.0, 0.5142857142857143), (11.0, 0.0), (4.0, 0.984375), (4.0, 0.984375), (4.0, 0.984375), (2.0, 0.5142857142857143), (4.0, 0.984375), (4.0, 0.984375), (0.0, 0.0)]
fuzzy :  None
pembilang :  21.744642857142857
penyebut :  5.9504464285714285
rata-rata tertimbang :  3.6542876434841323

[2.0, 2.0, 2.0, 2.0, 2.0, 2.7341772151898733, 4.0, 4.0, 11.0]
min :  2.0
max :  11.0
mean :  3.5260196905766525
fuzzy :  [(2.0, 0.0), (2.0, 0.0), (2.0, 0.0), (4.0, 0.9365826119683854), (2.0, 0.0), (11.0, 0.0), (4.0, 0.9365826119683854), (2.7341772151898733, 0.4811059907834101), (2.0, 0.0)]
fuzzy :  None
pembilang :  8.808089933838433
penyebut :  2.354271214720181
rata-rata tertimbang :  3.741323378022666

[0.0, 0.0, 2.0, 11.0, 14.0, 16.0, 16.0, 16.0, 16.0]
min :  0.0
max :  16.0
mean :  10.11111111111111
fuzzy :  [(2.0, 0.19780219780219782), (11.0, 0.8490566037735848), (0.0, 0.0), (16.0, 0.0), (14.0, 0.33962264150943394), (0.0, 0.0), (16.0, 0.0), (16.0, 0.0), (16.0, 0.0)]
fuzzy :  None
pembilang :  14.489944018245904
penyebut :  1.3864814430852166
rata-rata tertimbang :  10.450874831763123

[0.0, 0.0, 2.0, 2.0, 4.0, 4.0, 4.055131467345207, 11.0, 14.0]
min :  0.0
max :  14.0
mean :  4.561681274149468
fuzzy :  [(14.0, 0.0), (4.055131467345207, 0.8889554582265927), (2.0, 0.4384348400958598), (4.0, 0.8768696801917196), (2.0, 0.4384348400958598), (0.0, 0.0), (4.0, 0.8768696801917196), (0.0, 0.0), (11.0, 0.3178532201697454)]
fuzzy :  None
pembilang :  15.869913475507328
penyebut :  3.8374177189714973
rata-rata tertimbang :  4.135571010955975

[0.0, 0.0, 2.0, 2.0, 4.0, 4.0, 4.0, 11.0, 14.0]
min :  0.0
max :  14.0
mean :  4.555555555555555
fuzzy :  [(4.0, 0.8780487804878049), (0.0, 0.0), (4.0, 0.8780487804878049), (2.0, 0.43902439024390244), (11.0, 0.3176470588235294), (4.0, 0.8780487804878049), (0.0, 0.0), (14.0, 0.0), (2.0, 0.43902439024390244)]
fuzzy :  None
pembilang :  15.786800573888092
penyebut :  3.8298421807747487
rata-rata tertimbang :  4.122049898853676

[0.0, 0.0, 0.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
median :  5
min :  0.0
max :  4.0
mean :  2.6666666666666665
fuzzy :  [(0.0, 4.0), (0.0, 4.0), (0.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0)]
fuzzy :  4.0
pembilang :  96.0
penyebut :  36.0
rata-rata tertimbang :  4.0

In [ ]:
dummy.describe()

# Klasifikasi

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [ ]:
x = dummy.values
y = df.iloc[:, -1].values

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=94)

In [ ]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)