In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from scipy.spatial.distance import euclidean

In [2]:
df = pd.read_csv("transfusion_5%.csv")

In [3]:
df

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,2.0,50.0,12500.0,98.0,1.0
1,NaN,13.0,3250.0,NaN,1.0
2,1.0,16.0,4000.0,35.0,1.0
3,2.0,NaN,5000.0,45.0,1.0
4,1.0,24.0,6000.0,77.0,0.0
...,...,...,...,...,...
743,NaN,2.0,500.0,38.0,0.0
744,21.0,2.0,500.0,52.0,0.0
745,23.0,NaN,750.0,62.0,0.0
746,39.0,1.0,250.0,39.0,0.0
747,72.0,1.0,250.0,72.0,0.0

In [4]:
df.dtypes

Recency (months)                              float64
Frequency (times)                             float64
Monetary (c.c. blood)                         float64
Time (months)                                 float64
whether he/she donated blood in March 2007    float64
dtype: object

In [5]:
df.isnull().sum()

Recency (months)                              46
Frequency (times)                             46
Monetary (c.c. blood)                         55
Time (months)                                 40
whether he/she donated blood in March 2007     0
dtype: int64

In [6]:
df.isnull().sum().sum()

187

In [7]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

Recency (months)                              6.149733
Frequency (times)                             6.149733
Monetary (c.c. blood)                         7.352941
Time (months)                                 5.347594
whether he/she donated blood in March 2007    0.000000
dtype: float64

In [8]:
null_counts = df.isnull().sum().sum()
total = df.size
null_percentages = 100 * null_counts / total
print("total nilai :",total)
print("nilai hilang :",null_counts)
print("persentase :",null_percentages)

total nilai : 3740
nilai hilang : 187
persentase : 5.0

In [9]:
def jarak(df2,col):
    euc_dist[col] = []
    euc_dist_append =euc_dist[col].append
    for row in range(df2.shape[0]):
        current = df2.index[df2.iloc[:,col] == 0].tolist()
        current = current[0]
        a = df2.iloc[current,col+1:].tolist()
        b = df2.iloc[current,:col].tolist()
        x1 = b+a
        if(row is not current):
            a=df2.iloc[row,col+1:].tolist()
            b=df2.iloc[row,:col].tolist()
            x2=b+a
        else:
            continue
        dist = euclidean(x1,x2)
        euc_dist_append([dist,df2.iloc[row,col]])
#         print(" x1 = ",x1,"\n x2 = ",x2,"\n distance = ",euc_dist[col])

    lst = list(euc_dist[col])
    lst.sort()
    euc_dist[col] = lst
#     print(euc_dist[col])

In [10]:
from collections import Counter

def hitung(val, k, temp=None, i=0, counter=0):
    counts = Counter(val)
    total_count = len(counts)
#     print("jumlah val:", total_count)
    if counter >= int((k/2)+1) and total_count <= 2 :
        print("median : ",int((k/2)+1))
        return temp
    elif i is not k:
        if temp is None:
            temp = val[i]
        elif temp != val[i]:
            temp = val[i]
            counter = 0
        # print(f"temp = {temp} , counter = {counter} , i = {i} , k = {k} , median = {int((k/2)+1)}, val[i] = {val[i]}")
        return hitung(val,k,temp,i+1,counter+1)
    else:
        return None    

def Final(df,col,k):
    terdekat = []
    mean = 0
    minimum = None
    maximum = None
    fuzzy_val = []
    euc_val = []
    terdekat_append = terdekat.append
    fuzzy_append = fuzzy_val.append
    
    for val in range(k):
        terdekat_append(euc_dist[col][val])
    
    for x,y in terdekat:
        if (minimum is None or maximum is None):
            minimum = y
            maximum = y
        elif(y<minimum):
            minimum = y
        elif(y>maximum):
            maximum = y
        mean += y
        euc_val.append(y)
    mean /= len(terdekat)
    euc_val.sort()
    print(euc_val)
    
    fuzzy = hitung(euc_val,9)
    print("min : ",minimum)
    print("max : ",maximum)
    print("mean : ",mean)
    for x,y in terdekat:
        if fuzzy is None:
            fuzzy_append((y,fuzzy_triangular(y,minimum,mean,maximum)))
        else:
            fuzzy_val.append((y,fuzzy))
        
    print("fuzzy : ",fuzzy_val)
    print("fuzzy : ",fuzzy)
    
    pembilang = 0
    penyebut = 0 
    
    for nilai,bobot in fuzzy_val:
        pembilang += nilai*bobot
        penyebut += bobot
            
    print("pembilang : ", pembilang)
    print("penyebut : ",penyebut)
    
    if fuzzy is not None:
        tertimbang = fuzzy
    else:
        tertimbang = pembilang / penyebut
    
    print("rata-rata tertimbang : ",tertimbang)
    index = dummy.index[dummy.iloc[:,col] == 0].tolist()
    index = index[0]
    
    if tertimbang == 0:
        tertimbang = dummy.iloc[index-1, col]
    
    dummy.iloc[index,col] = tertimbang
    print(" ")

In [11]:
def fuzzy_triangular(val, minimum, mean, maximum):
   if val <= minimum or val >= maximum: 
        return 0.0
   elif minimum < val <= mean:
        return float((val - minimum)/(mean - minimum)) 
   elif mean < val < maximum:
        return float((maximum - val)/(maximum - mean))

In [12]:
data = df.iloc[:, :-1]
df2 = df.copy()
dummy = df2.fillna(0)
dummy

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,2.0,50.0,12500.0,98.0,1.0
1,0.0,13.0,3250.0,0.0,1.0
2,1.0,16.0,4000.0,35.0,1.0
3,2.0,0.0,5000.0,45.0,1.0
4,1.0,24.0,6000.0,77.0,0.0
...,...,...,...,...,...
743,0.0,2.0,500.0,38.0,0.0
744,21.0,2.0,500.0,52.0,0.0
745,23.0,0.0,750.0,62.0,0.0
746,39.0,1.0,250.0,39.0,0.0
747,72.0,1.0,250.0,72.0,0.0

In [13]:
euc_dist = {}

In [ ]:
for i in range(df2.shape[1]):
    print("Kolom :",i+1)
    current = dummy.index[dummy.iloc[:,i] == 0].tolist()
    for x in current:
        jarak(dummy,i)
        Final(dummy,i,9)
dummy

Kolom : 1
[1.0, 2.0, 2.0, 2.0, 2.0, 4.0, 12.0, 14.0, 21.0]
min :  1.0
max :  21.0
mean :  6.666666666666667
fuzzy :  [(12.0, 0.627906976744186), (2.0, 0.1764705882352941), (4.0, 0.5294117647058824), (1.0, 0.0), (2.0, 0.1764705882352941), (14.0, 0.48837209302325585), (21.0, 0.0), (2.0, 0.1764705882352941), (2.0, 0.1764705882352941)]
fuzzy :  None
pembilang :  17.901504787961695
penyebut :  2.3515731874145005
rata-rata tertimbang :  7.612565445026178

[2.0, 2.0, 2.0, 2.0, 2.0, 4.0, 4.0, 14.0, 14.0]
min :  2.0
max :  14.0
mean :  5.111111111111111
fuzzy :  [(2.0, 0.0), (2.0, 0.0), (2.0, 0.0), (2.0, 0.0), (4.0, 0.6428571428571429), (14.0, 0.0), (14.0, 0.0), (4.0, 0.6428571428571429), (2.0, 0.0)]
fuzzy :  None
pembilang :  5.142857142857143
penyebut :  1.2857142857142858
rata-rata tertimbang :  4.0

[1.0, 2.0, 2.0, 4.0, 4.0, 7.0, 8.0, 12.0, 23.0]
min :  1.0
max :  23.0
mean :  7.0
fuzzy :  [(23.0, 0.0), (2.0, 0.16666666666666666), (8.0, 0.9375), (12.0, 0.6875), (7.0, 1.0), (2.0, 0.16666666666666666), (1.0, 0.0), (4.0, 0.5), (4.0, 0.5)]
fuzzy :  None
pembilang :  27.416666666666664
penyebut :  3.9583333333333335
rata-rata tertimbang :  6.9263157894736835

[0.0, 2.0, 2.0, 2.0, 2.0, 4.0, 4.0, 4.0, 4.0]
min :  0.0
max :  4.0
mean :  2.6666666666666665
fuzzy :  [(4.0, 0.0), (2.0, 0.75), (2.0, 0.75), (4.0, 0.0), (4.0, 0.0), (2.0, 0.75), (2.0, 0.75), (4.0, 0.0), (0.0, 0.0)]
fuzzy :  None
pembilang :  6.0
penyebut :  3.0
rata-rata tertimbang :  2.0

[0.0, 0.0, 1.0, 2.0, 4.0, 4.0, 9.0, 11.0, 11.0]
min :  0.0
max :  11.0
mean :  4.666666666666667
fuzzy :  [(1.0, 0.21428571428571427), (2.0, 0.42857142857142855), (0.0, 0.0), (4.0, 0.8571428571428571), (4.0, 0.8571428571428571), (11.0, 0.0), (0.0, 0.0), (9.0, 0.31578947368421056), (11.0, 0.0)]
fuzzy :  None
pembilang :  10.770676691729324
penyebut :  2.672932330827068
rata-rata tertimbang :  4.029535864978903

[2.0, 4.0, 11.0, 14.0, 14.0, 15.0, 21.0, 21.0, 23.0]
min :  2.0
max :  23.0
mean :  13.88888888888889
fuzzy :  [(2.0, 0.0), (14.0, 0.9878048780487805), (4.0, 0.16822429906542055), (14.0, 0.9878048780487805), (23.0, 0.0), (15.0, 0.8780487804878049), (21.0, 0.21951219512195122), (11.0, 0.7570093457943925), (21.0, 0.21951219512195122)]
fuzzy :  None
pembilang :  59.048780487804876
penyebut :  4.217916571689082
rata-rata tertimbang :  13.999513618677042

[0.0, 0.0, 4.0, 4.0, 4.0, 9.0, 9.0, 11.0, 11.0]
min :  0.0
max :  11.0
mean :  5.777777777777778
fuzzy :  [(4.0, 0.6923076923076923), (4.0, 0.6923076923076923), (11.0, 0.0), (0.0, 0.0), (4.0, 0.6923076923076923), (9.0, 0.3829787234042553), (11.0, 0.0), (0.0, 0.0), (9.0, 0.3829787234042553)]
fuzzy :  None
pembilang :  15.201309328968904
penyebut :  2.842880523731587
rata-rata tertimbang :  5.347150259067359

[0.0, 4.0, 4.0, 4.0, 4.0, 9.0, 9.0, 11.0, 11.0]
min :  0.0
max :  11.0
mean :  6.222222222222222
fuzzy :  [(9.0, 0.4186046511627907), (11.0, 0.0), (4.0, 0.6428571428571428), (11.0, 0.0), (0.0, 0.0), (4.0, 0.6428571428571428), (4.0, 0.6428571428571428), (9.0, 0.4186046511627907), (4.0, 0.6428571428571428)]
fuzzy :  None
pembilang :  17.820598006644516
penyebut :  3.4086378737541527
rata-rata tertimbang :  5.228070175438596

[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 4.0, 4.0, 11.0]
min :  2.0
max :  11.0
mean :  3.4444444444444446
fuzzy :  [(2.0, 0.0), (2.0, 0.0), (4.0, 0.9264705882352942), (2.0, 0.0), (2.0, 0.0), (11.0, 0.0), (2.0, 0.0), (2.0, 0.0), (4.0, 0.9264705882352942)]
fuzzy :  None
pembilang :  7.411764705882353
penyebut :  1.8529411764705883
rata-rata tertimbang :  4.0

[2.0, 2.0, 2.0, 2.0, 4.0, 4.0, 4.0, 4.0, 4.0]
median :  5
min :  2.0
max :  4.0
mean :  3.111111111111111
fuzzy :  [(2.0, 4.0), (2.0, 4.0), (2.0, 4.0), (2.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0)]
fuzzy :  4.0
pembilang :  112.0
penyebut :  36.0
rata-rata tertimbang :  4.0

[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 4.0, 10.0, 11.0]
min :  2.0
max :  11.0
mean :  4.111111111111111
fuzzy :  [(2.0, 0.0), (2.0, 0.0), (2.0, 0.0), (2.0, 0.0), (10.0, 0.14516129032258063), (2.0, 0.0), (11.0, 0.0), (2.0, 0.0), (4.0, 0.9473684210526317)]
fuzzy :  None
pembilang :  5.2410865874363335
penyebut :  1.0925297113752124
rata-rata tertimbang :  4.7972027972027975

[2.0, 2.0, 2.0, 4.0, 4.0, 4.0, 10.0, 13.0, 14.0]
min :  2.0
max :  14.0
mean :  6.111111111111111
fuzzy :  [(2.0, 0.0), (2.0, 0.0), (10.0, 0.5070422535211268), (4.0, 0.4864864864864865), (4.0, 0.4864864864864865), (4.0, 0.4864864864864865), (13.0, 0.1267605633802817), (14.0, 0.0), (2.0, 0.0)]
fuzzy :  None
pembilang :  12.556147696992767
penyebut :  2.0932622763608677
rata-rata tertimbang :  5.998363338788871

[4.0, 4.0, 4.0, 4.0, 5.228070175438596, 9.0, 9.0, 11.0, 11.0]
min :  4.0
max :  11.0
mean :  6.803118908382066
fuzzy :  [(9.0, 0.47654435671156525), (11.0, 0.0), (4.0, 0.0), (5.228070175438596, 0.4381084840055631), (9.0, 0.47654435671156525), (4.0, 0.0), (11.0, 0.0), (4.0, 0.0), (4.0, 0.0)]
fuzzy :  None
pembilang :  10.868260319644277
penyebut :  1.3911971974286936
rata-rata tertimbang :  7.812163753443253

[2.0, 3.0, 4.0, 4.0, 4.0, 14.0, 14.0, 14.0, 16.0]
min :  2.0
max :  16.0
mean :  8.333333333333334
fuzzy :  [(3.0, 0.15789473684210525), (14.0, 0.2608695652173913), (4.0, 0.3157894736842105), (16.0, 0.0), (4.0, 0.3157894736842105), (14.0, 0.2608695652173913), (14.0, 0.2608695652173913), (4.0, 0.3157894736842105), (2.0, 0.0)]
fuzzy :  None
pembilang :  15.219679633867278
penyebut :  1.887871853546911
rata-rata tertimbang :  8.06181818181818

[0.0, 4.0, 8.0, 11.0, 11.0, 14.0, 14.0, 14.0, 23.0]
min :  0.0
max :  23.0
mean :  11.0
fuzzy :  [(23.0, 0.0), (8.0, 0.7272727272727273), (11.0, 1.0), (14.0, 0.75), (4.0, 0.36363636363636365), (14.0, 0.75), (0.0, 0.0), (11.0, 1.0), (14.0, 0.75)]
fuzzy :  None
pembilang :  60.77272727272727
penyebut :  5.340909090909092
rata-rata tertimbang :  11.378723404255318

[2.0, 2.0, 2.0, 4.0, 14.0, 14.0, 16.0, 16.0, 16.0]
min :  2.0
max :  16.0
mean :  9.555555555555555
fuzzy :  [(16.0, 0.0), (14.0, 0.3103448275862069), (2.0, 0.0), (14.0, 0.3103448275862069), (16.0, 0.0), (16.0, 0.0), (2.0, 0.0), (2.0, 0.0), (4.0, 0.2647058823529412)]
fuzzy :  None
pembilang :  9.748478701825558
penyebut :  0.885395537525355
rata-rata tertimbang :  11.010309278350515

[2.0, 2.0, 2.0, 2.0, 9.0, 11.0, 11.0, 11.0, 11.0]
min :  2.0
max :  11.0
mean :  6.777777777777778
fuzzy :  [(2.0, 0.0), (2.0, 0.0), (9.0, 0.47368421052631576), (11.0, 0.0), (11.0, 0.0), (11.0, 0.0), (11.0, 0.0), (2.0, 0.0), (2.0, 0.0)]
fuzzy :  None
pembilang :  4.263157894736842
penyebut :  0.47368421052631576
rata-rata tertimbang :  9.0

[2.0, 2.0, 2.0, 2.0, 4.0, 5.0, 7.0, 9.0, 11.0]
min :  2.0
max :  11.0
mean :  4.888888888888889
fuzzy :  [(2.0, 0.0), (5.0, 0.9818181818181819), (2.0, 0.0), (7.0, 0.6545454545454545), (4.0, 0.6923076923076922), (9.0, 0.32727272727272727), (2.0, 0.0), (2.0, 0.0), (11.0, 0.0)]
fuzzy :  None
pembilang :  15.205594405594406
penyebut :  2.655944055944056
rata-rata tertimbang :  5.725118483412323

[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 4.0, 4.0, 11.0]
min :  2.0
max :  11.0
mean :  3.4444444444444446
fuzzy :  [(2.0, 0.0), (2.0, 0.0), (2.0, 0.0), (4.0, 0.9264705882352942), (4.0, 0.9264705882352942), (11.0, 0.0), (2.0, 0.0), (2.0, 0.0), (2.0, 0.0)]
fuzzy :  None
pembilang :  7.411764705882353
penyebut :  1.8529411764705883
rata-rata tertimbang :  4.0

[0.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
median :  5
min :  0.0
max :  4.0
mean :  3.5555555555555554
fuzzy :  [(0.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0)]
fuzzy :  4.0
pembilang :  128.0
penyebut :  36.0
rata-rata tertimbang :  4.0

[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
median :  5
min :  4.0
max :  4.0
mean :  4.0
fuzzy :  [(4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0)]
fuzzy :  4.0
pembilang :  144.0
penyebut :  36.0
rata-rata tertimbang :  4.0

[0.0, 2.0, 2.0, 2.0, 4.0, 11.0, 14.0, 21.0, 23.0]
min :  0.0
max :  23.0
mean :  8.777777777777779
fuzzy :  [(0.0, 0.0), (4.0, 0.45569620253164556), (11.0, 0.84375), (14.0, 0.6328125), (21.0, 0.140625), (23.0, 0.0), (2.0, 0.22784810126582278), (2.0, 0.22784810126582278), (2.0, 0.22784810126582278)]
fuzzy :  None
pembilang :  24.283623417721515
penyebut :  2.7564280063291133
rata-rata tertimbang :  8.809815950920246

[0.0, 0.0, 11.0, 16.0, 21.0, 21.0, 21.0, 23.0, 23.0]
min :  0.0
max :  23.0
mean :  15.11111111111111
fuzzy :  [(0.0, 0.0), (21.0, 0.2535211267605634), (21.0, 0.2535211267605634), (11.0, 0.7279411764705882), (23.0, 0.0), (0.0, 0.0), (16.0, 0.8873239436619718), (21.0, 0.2535211267605634), (23.0, 0.0)]
fuzzy :  None
pembilang :  38.17636702568351
penyebut :  2.3758285004142503
rata-rata tertimbang :  16.068654374264415

[0.0, 4.0, 4.0, 4.0, 8.0, 11.0, 14.0, 14.0, 23.0]
min :  0.0
max :  23.0
mean :  9.11111111111111
fuzzy :  [(0.0, 0.0), (14.0, 0.648), (23.0, 0.0), (4.0, 0.43902439024390244), (4.0, 0.43902439024390244), (14.0, 0.648), (4.0, 0.43902439024390244), (8.0, 0.8780487804878049), (11.0, 0.864)]
fuzzy :  None
pembilang :  39.94068292682927
penyebut :  4.3551219512195125
rata-rata tertimbang :  9.170967741935483

[0.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 14.0]
min :  0.0
max :  14.0
mean :  3.111111111111111
fuzzy :  [(0.0, 0.0), (2.0, 0.6428571428571428), (14.0, 0.0), (2.0, 0.6428571428571428), (2.0, 0.6428571428571428), (2.0, 0.6428571428571428), (2.0, 0.6428571428571428), (2.0, 0.6428571428571428), (2.0, 0.6428571428571428)]
fuzzy :  None
pembilang :  9.0
penyebut :  4.5
rata-rata tertimbang :  2.0

[0.0, 2.0, 4.0, 4.0, 14.0, 14.0, 16.0, 16.0, 21.0]
min :  0.0
max :  21.0
mean :  10.11111111111111
fuzzy :  [(0.0, 0.0), (14.0, 0.6428571428571428), (16.0, 0.45918367346938777), (14.0, 0.6428571428571428), (2.0, 0.19780219780219782), (16.0, 0.45918367346938777), (21.0, 0.0), (4.0, 0.39560439560439564), (4.0, 0.39560439560439564)]
fuzzy :  None
pembilang :  36.25431711145997
penyebut :  3.19309262166405
rata-rata tertimbang :  11.353982300884956

[0.0, 2.0, 3.0, 4.0, 4.0, 11.0, 14.0, 14.0, 16.0]
min :  0.0
max :  16.0
mean :  7.555555555555555
fuzzy :  [(0.0, 0.0), (2.0, 0.2647058823529412), (16.0, 0.0), (11.0, 0.5921052631578947), (14.0, 0.23684210526315788), (4.0, 0.5294117647058824), (14.0, 0.23684210526315788), (4.0, 0.5294117647058824), (3.0, 0.3970588235294118)]
fuzzy :  None
pembilang :  19.100619195046438
penyebut :  2.786377708978328
rata-rata tertimbang :  6.8549999999999995

[0.0, 2.0, 2.0, 3.0, 11.0, 18.0, 21.0, 21.0, 21.0]
min :  0.0
max :  21.0
mean :  11.0
fuzzy :  [(0.0, 0.0), (11.0, 1.0), (21.0, 0.0), (2.0, 0.18181818181818182), (21.0, 0.0), (2.0, 0.18181818181818182), (3.0, 0.2727272727272727), (18.0, 0.3), (21.0, 0.0)]
fuzzy :  None
pembilang :  17.945454545454545
penyebut :  1.9363636363636365
rata-rata tertimbang :  9.267605633802816

[0.0, 16.0, 16.068654374264415, 21.0, 21.0, 21.0, 23.0, 23.0, 23.0]
min :  0.0
max :  23.0
mean :  18.229850486029378
fuzzy :  [(0.0, 0.0), (16.0, 0.8776813618006223), (21.0, 0.41927406974194), (23.0, 0.0), (23.0, 0.0), (23.0, 0.0), (16.068654374264415, 0.8814474033442449), (21.0, 0.41927406974194), (21.0, 0.41927406974194)]
fuzzy :  None
pembilang :  54.620841855983684
penyebut :  3.016950974370687
rata-rata tertimbang :  18.10465013186937

In [ ]:
dummy.describe()

# Klasifikasi

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [ ]:
x = dummy.values
y = df.iloc[:, -1].values

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=72)

In [ ]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)