In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("audit_5%.csv")

In [3]:
df

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,4.18,0.6,2.508,2.50,0.2,0.500,6.68,5.0,0.2,...,NaN,0.0,0.2,0.0,2.4,8.574,0.4,0.5,NaN,1.0
1,NaN,0.00,NaN,0.000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0.0
2,3.89,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096,0.0
3,3.89,0.00,0.2,NaN,10.80,0.6,6.480,NaN,6.0,0.6,...,0.4,0.0,0.2,NaN,4.4,17.530,0.4,0.5,3.5060,1.0
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.08,NaN,0.2,...,0.4,NaN,NaN,0.0,2.0,1.416,0.4,0.5,0.2832,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,NaN,0.49,0.2,0.098,0.40,0.2,0.080,0.89,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.578,0.4,NaN,0.3156,0.0
772,55.57,0.47,0.2,0.094,0.37,0.2,0.074,0.84,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.568,0.4,0.5,0.3136,0.0
773,55.57,0.24,0.2,NaN,0.04,0.2,0.008,0.28,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.456,0.4,0.5,0.2912,0.0
774,55.57,0.20,0.2,0.040,0.00,0.2,0.000,0.20,NaN,0.2,...,0.4,0.0,0.2,0.0,2.0,1.440,0.4,0.5,0.2880,0.0
775,55.57,0.00,0.2,0.000,0.00,0.2,NaN,0.00,5.0,0.2,...,NaN,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928,0.0

In [4]:
df.isnull().sum()

Sector_score      56
PARA_A            46
Score_A           38
Risk_A            46
PARA_B            43
Score_B           39
Risk_B            46
TOTAL             34
numbers           38
Score_B.1         26
Risk_C            41
Money_Value       43
Score_MV          35
Risk_D            35
District_Loss     24
PROB              45
RiSk_E            48
History           48
Prob              43
Risk_F            40
Score             37
Inherent_Risk     33
CONTROL_RISK      35
Detection_Risk    42
Audit_Risk        49
Risk               0
dtype: int64

In [5]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

Sector_score      7.216495
PARA_A            5.927835
Score_A           4.896907
Risk_A            5.927835
PARA_B            5.541237
Score_B           5.025773
Risk_B            5.927835
TOTAL             4.381443
numbers           4.896907
Score_B.1         3.350515
Risk_C            5.283505
Money_Value       5.541237
Score_MV          4.510309
Risk_D            4.510309
District_Loss     3.092784
PROB              5.798969
RiSk_E            6.185567
History           6.185567
Prob              5.541237
Risk_F            5.154639
Score             4.768041
Inherent_Risk     4.252577
CONTROL_RISK      4.510309
Detection_Risk    5.412371
Audit_Risk        6.314433
Risk              0.000000
dtype: float64

In [6]:
null_counts = df.isnull().sum().sum()
total = df.size
null_percentages = 100 * null_counts / total
print("total nilai :",total)
print("nilai hilang :",null_counts)
print("persentase hilang :",null_percentages)

total nilai : 20176
nilai hilang : 1010
persentase hilang : 5.005947660586836

# Imputasi Mean

In [7]:
df2 = df.fillna(df.mean())

In [8]:
df2

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.890000,4.18,0.600000,2.508000,2.50,0.2,0.500000,6.680000,5.000000,0.2,...,0.518681,0.000000,0.200000,0.000000,2.4,8.574,0.4,0.5,7.097313,1.0
1,20.197861,0.00,0.352304,0.000000,4.83,0.2,0.966000,4.830000,5.000000,0.2,...,0.400000,0.000000,0.200000,0.000000,2.0,2.554,0.4,0.5,0.510800,0.0
2,3.890000,0.51,0.200000,0.102000,0.23,0.2,0.046000,0.740000,5.000000,0.2,...,0.400000,0.000000,0.200000,0.000000,2.0,1.548,0.4,0.5,0.309600,0.0
3,3.890000,0.00,0.200000,1.364112,10.80,0.6,6.480000,13.239113,6.000000,0.6,...,0.400000,0.000000,0.200000,0.055435,4.4,17.530,0.4,0.5,3.506000,1.0
4,3.890000,0.00,0.200000,0.000000,0.08,0.2,0.016000,0.080000,5.067073,0.2,...,0.400000,0.107143,0.217462,0.000000,2.0,1.416,0.4,0.5,0.283200,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,20.197861,0.49,0.200000,0.098000,0.40,0.2,0.080000,0.890000,5.000000,0.2,...,0.400000,0.000000,0.200000,0.000000,2.0,1.578,0.4,0.5,0.315600,0.0
772,55.570000,0.47,0.200000,0.094000,0.37,0.2,0.074000,0.840000,5.000000,0.2,...,0.400000,0.000000,0.200000,0.000000,2.0,1.568,0.4,0.5,0.313600,0.0
773,55.570000,0.24,0.200000,1.364112,0.04,0.2,0.008000,0.280000,5.000000,0.2,...,0.400000,0.000000,0.200000,0.000000,2.0,1.456,0.4,0.5,0.291200,0.0
774,55.570000,0.20,0.200000,0.040000,0.00,0.2,0.000000,0.200000,5.067073,0.2,...,0.400000,0.000000,0.200000,0.000000,2.0,1.440,0.4,0.5,0.288000,0.0
775,55.570000,0.00,0.200000,0.000000,0.00,0.2,6.435313,0.000000,5.000000,0.2,...,0.518681,0.000000,0.200000,0.000000,2.0,1.464,0.4,0.5,0.292800,0.0

In [9]:
df2.describe()

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
count,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,...,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.0,776.000000,776.000000
mean,20.197861,2.359302,0.352304,1.364112,10.860503,0.314518,6.435313,13.239113,5.067073,0.223733,...,0.518681,0.107143,0.217462,0.055435,2.690122,17.703831,0.573819,0.5,7.097313,0.393041
std,23.433475,4.686148,0.169710,3.403379,49.792344,0.166073,29.962447,51.135583,0.257607,0.078843,...,0.277095,0.527493,0.067551,0.305093,0.830731,54.437481,0.438902,0.0,38.233615,0.488741
min,1.850000,0.000000,0.200000,0.000000,0.000000,0.200000,0.000000,0.000000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.000000,1.400000,0.400000,0.5,0.280000,0.000000
25%,2.370000,0.270000,0.200000,0.058000,0.000000,0.200000,0.000000,0.590000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.000000,1.590000,0.400000,0.5,0.319200,0.000000
50%,3.890000,1.035000,0.276152,0.402000,0.535000,0.200000,0.099000,1.495000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.400000,2.276000,0.400000,0.5,0.685200,0.000000
75%,55.570000,2.422500,0.600000,1.366584,6.545000,0.400000,3.454500,9.670000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,3.200000,15.300500,0.573819,0.5,4.964400,1.000000
max,59.850000,85.000000,0.600000,51.000000,1264.630000,0.600000,758.778000,1268.910000,9.000000,0.600000,...,2.400000,9.000000,0.600000,5.400000,5.200000,801.262000,5.800000,0.5,961.514400,1.000000

# Klasifikasi

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [11]:
x = df2.iloc[:, :-1].values
y = df2.iloc[:, -1].values

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=2)

In [29]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [30]:
classifier = GaussianNB()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[129   1]
 [  8  56]]
0.9536082474226805

In [31]:
classifier = MLPClassifier(hidden_layer_sizes=3, learning_rate_init=0.1, max_iter=100)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[126   4]
 [  2  62]]
0.9690721649484536