In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from scipy.spatial.distance import euclidean
import multiprocessing

In [2]:
df = pd.read_csv("audit_risk.csv")

In [3]:
df

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,4.18,0.6,2.508,2.50,0.2,0.500,6.68,5.0,0.2,...,0.4,0,0.2,0.0,2.4,8.574,0.4,0.5,1.7148,1
1,3.89,0.00,0.2,0.000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.4,0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0
2,3.89,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096,0
3,3.89,0.00,0.2,0.000,10.80,0.6,6.480,10.80,6.0,0.6,...,0.4,0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060,1
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.08,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.416,0.4,0.5,0.2832,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,55.57,0.49,0.2,0.098,0.40,0.2,0.080,0.89,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.578,0.4,0.5,0.3156,0
772,55.57,0.47,0.2,0.094,0.37,0.2,0.074,0.84,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.568,0.4,0.5,0.3136,0
773,55.57,0.24,0.2,0.048,0.04,0.2,0.008,0.28,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.456,0.4,0.5,0.2912,0
774,55.57,0.20,0.2,0.040,0.00,0.2,0.000,0.20,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.440,0.4,0.5,0.2880,0
775,55.57,0.00,0.2,0.000,0.00,0.2,0.000,0.00,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928,0

In [4]:
df.dtypes

Sector_score      float64
PARA_A            float64
Score_A           float64
Risk_A            float64
PARA_B            float64
Score_B           float64
Risk_B            float64
TOTAL             float64
numbers           float64
Score_B.1         float64
Risk_C            float64
Money_Value       float64
Score_MV          float64
Risk_D            float64
District_Loss       int64
PROB              float64
RiSk_E            float64
History             int64
Prob              float64
Risk_F            float64
Score             float64
Inherent_Risk     float64
CONTROL_RISK      float64
Detection_Risk    float64
Audit_Risk        float64
Risk                int64
dtype: object

In [5]:
total_values = df.iloc[:, :-1].size
total_values

19400

In [6]:
values_to_drop = int(total_values * 0.05)
values_to_drop

970

In [7]:
# Generate random indices for values to be dropped
drop_indices = np.random.choice(total_values, values_to_drop, replace=False)
dataset = df.iloc[:, :-1]

# Replace the selected values with NaN
dataset.values.flat[drop_indices] = np.nan

In [8]:
df

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,4.18,0.6,2.508,2.50,0.2,0.500,6.68,5.0,0.2,...,0.4,0,0.2,0.0,2.4,8.574,0.4,0.5,1.7148,1
1,3.89,0.00,0.2,0.000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.4,0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0
2,3.89,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096,0
3,3.89,0.00,0.2,0.000,10.80,0.6,6.480,10.80,6.0,0.6,...,0.4,0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060,1
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.08,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.416,0.4,0.5,0.2832,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,55.57,0.49,0.2,0.098,0.40,0.2,0.080,0.89,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.578,0.4,0.5,0.3156,0
772,55.57,0.47,0.2,0.094,0.37,0.2,0.074,0.84,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.568,0.4,0.5,0.3136,0
773,55.57,0.24,0.2,0.048,0.04,0.2,0.008,0.28,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.456,0.4,0.5,0.2912,0
774,55.57,0.20,0.2,0.040,0.00,0.2,0.000,0.20,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.440,0.4,0.5,0.2880,0
775,55.57,0.00,0.2,0.000,0.00,0.2,0.000,0.00,5.0,0.2,...,0.4,0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928,0

In [9]:
df.isnull().sum()

Sector_score      0
PARA_A            0
Score_A           0
Risk_A            0
PARA_B            0
Score_B           0
Risk_B            0
TOTAL             0
numbers           0
Score_B.1         0
Risk_C            0
Money_Value       0
Score_MV          0
Risk_D            0
District_Loss     0
PROB              0
RiSk_E            0
History           0
Prob              0
Risk_F            0
Score             0
Inherent_Risk     0
CONTROL_RISK      0
Detection_Risk    0
Audit_Risk        0
Risk              0
dtype: int64

In [11]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

Sector_score      5.283505
PARA_A            7.216495
Score_A           5.154639
Risk_A            4.768041
PARA_B            3.994845
Score_B           5.283505
Risk_B            4.768041
TOTAL             5.025773
numbers           3.479381
Score_B.1         5.283505
Risk_C            5.412371
Money_Value       4.896907
Score_MV          5.670103
Risk_D            4.896907
District_Loss     4.768041
PROB              3.608247
RiSk_E            4.510309
History           5.541237
Prob              4.510309
Risk_F            4.896907
Score             4.510309
Inherent_Risk     6.056701
CONTROL_RISK      5.283505
Detection_Risk    4.639175
Audit_Risk        5.541237
Risk              0.000000
dtype: float64

# Imputasi

In [12]:
def jarak(df2,col):
    euc_dist[col] = []
    for row in range(df2.shape[0]):
        current = df2.index[df2.iloc[:,col] == 0].tolist()
        current = current[0]
        a = df2.iloc[current,col+1:].tolist()
        b = df2.iloc[current,:col].tolist()
        x1 = b+a
        if(row is not current):
            a=df2.iloc[row,col+1:].tolist()
            b=df2.iloc[row,:col].tolist()
            x2=b+a
        else:
            continue
        dist = euclidean(x1,x2)
        euc_dist[col].append([dist,df2.iloc[row,col]])
#         print(" x1 = ",x1,"\n x2 = ",x2,"\n distance = ",euc_dist[col])

    lst = list(euc_dist[col])
    lst.sort()
    euc_dist[col] = lst
#     print(euc_dist[col])

In [13]:
def Final(df,col,k):
    terdekat = []
    mean = 0
    minimum = None
    maximum = None
    fuzzy_val = []
    
    for val in range(k):
        terdekat.append(euc_dist[col][val])
    
    for x,y in terdekat:
        if (minimum is None or maximum is None):
            minimum = y
            maximum = y
        elif(y<minimum):
            minimum = y
        elif(y>maximum):
            maximum = y
        mean += y
    mean /= len(terdekat)
    for x,y in terdekat:
        fuzzy_val.append((y,fuzzy_triangular(y,minimum,mean,maximum)))

    pembilang = 0
    penyebut = 0
    y = 1
    for nilai,bobot in fuzzy_val:
        pembilang += nilai*bobot
        penyebut += bobot
        
        if (penyebut == 0):
            penyebut = y
    
    tertimbang = pembilang/penyebut
    index = dummy.index[dummy.iloc[:,col] == 0].tolist()
    index = index[0]
    dummy.iloc[index,col] = tertimbang

In [14]:
def fuzzy_triangular(val, minimum, mean, maximum):
   if val <= minimum or val >= maximum: 
        return 0.0
   elif minimum < val <= mean:
        return float((val - minimum)/(mean - minimum)) 
   elif mean < val < maximum:
        return float((maximum - val)/(maximum - mean))

In [15]:
df2 = dataset.copy()
dummy = df2.fillna(0)
dummy

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,PROB,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk
0,3.89,4.18,0.0,2.508,2.50,0.2,0.500,6.68,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.4,8.574,0.4,0.5,1.7148
1,3.89,0.00,0.2,0.000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108
2,3.89,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,0.2,...,0.2,0.4,0.0,0.0,0.0,2.0,1.548,0.4,0.5,0.3096
3,3.89,0.00,0.2,0.000,10.80,0.6,6.480,10.80,6.0,0.6,...,0.2,0.4,0.0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.08,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.416,0.4,0.5,0.2832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,0.00,0.49,0.2,0.098,0.40,0.2,0.000,0.89,5.0,0.2,...,0.2,0.0,0.0,0.2,0.0,2.0,1.578,0.4,0.5,0.3156
772,55.57,0.47,0.2,0.094,0.00,0.2,0.074,0.84,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.568,0.4,0.5,0.3136
773,55.57,0.24,0.2,0.048,0.04,0.2,0.008,0.28,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.456,0.4,0.5,0.2912
774,55.57,0.20,0.2,0.040,0.00,0.2,0.000,0.20,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.440,0.4,0.5,0.2880
775,55.57,0.00,0.2,0.000,0.00,0.2,0.000,0.00,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928

In [16]:
euc_dist = {}

In [17]:
for i in range(df2.shape[1]):
    current = dummy.index[dummy.iloc[:,i] == 0].tolist()
    for x in current:
        jarak(dummy,i)
        Final(dummy,i,3)
dummy

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,PROB,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk
0,3.89,4.18000,0.0,2.508000,2.50,0.2,0.500,6.68,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.4,8.574,0.4,0.5,1.7148
1,3.89,0.02000,0.2,0.004000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108
2,3.89,0.51000,0.2,0.102000,0.23,0.2,0.046,0.74,5.0,0.2,...,0.2,0.4,0.0,0.0,0.0,2.0,1.548,0.4,0.5,0.3096
3,3.89,0.62208,0.2,0.782478,10.80,0.6,6.480,10.80,6.0,0.6,...,0.2,0.4,0.0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060
4,3.89,0.00000,0.2,0.000000,0.08,0.2,0.016,0.08,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.416,0.4,0.5,0.2832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,0.00,0.49000,0.2,0.098000,0.40,0.2,0.000,0.89,5.0,0.2,...,0.2,0.0,0.0,0.2,0.0,2.0,1.578,0.4,0.5,0.3156
772,55.57,0.47000,0.2,0.094000,0.00,0.2,0.074,0.84,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.568,0.4,0.5,0.3136
773,55.57,0.24000,0.2,0.048000,0.04,0.2,0.008,0.28,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.456,0.4,0.5,0.2912
774,55.57,0.20000,0.2,0.040000,0.00,0.2,0.000,0.20,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.440,0.4,0.5,0.2880
775,55.57,0.00000,0.2,0.000000,0.00,0.2,0.000,0.00,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928

In [35]:
dummy

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,PROB,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk
0,3.89,4.18000,0.0,2.508000,2.50,0.2,0.500,6.68,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.4,8.574,0.4,0.5,1.7148
1,3.89,0.02000,0.2,0.004000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108
2,3.89,0.51000,0.2,0.102000,0.23,0.2,0.046,0.74,5.0,0.2,...,0.2,0.4,0.0,0.0,0.0,2.0,1.548,0.4,0.5,0.3096
3,3.89,0.62208,0.2,0.782478,10.80,0.6,6.480,10.80,6.0,0.6,...,0.2,0.4,0.0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060
4,3.89,0.00000,0.2,0.000000,0.08,0.2,0.016,0.08,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.416,0.4,0.5,0.2832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,0.00,0.49000,0.2,0.098000,0.40,0.2,0.000,0.89,5.0,0.2,...,0.2,0.0,0.0,0.2,0.0,2.0,1.578,0.4,0.5,0.3156
772,55.57,0.47000,0.2,0.094000,0.00,0.2,0.074,0.84,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.568,0.4,0.5,0.3136
773,55.57,0.24000,0.2,0.048000,0.04,0.2,0.008,0.28,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.456,0.4,0.5,0.2912
774,55.57,0.20000,0.2,0.040000,0.00,0.2,0.000,0.20,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.440,0.4,0.5,0.2880
775,55.57,0.00000,0.2,0.000000,0.00,0.2,0.000,0.00,5.0,0.2,...,0.2,0.4,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928

In [18]:
dummy.describe()

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,PROB,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk
count,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,...,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000
mean,19.373698,2.236369,0.331959,1.310707,10.507334,0.296392,6.196203,12.758132,4.892397,0.212887,...,0.198711,0.494330,0.095361,0.206443,0.051031,2.582990,17.466604,0.535309,0.476804,7.028429
std,24.197575,5.615380,0.185429,3.432812,49.921610,0.179137,30.042308,51.156331,0.966046,0.094433,...,0.053264,0.302708,0.521713,0.079415,0.302547,1.011633,54.758381,0.409425,0.105234,38.609407
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.370000,0.000000,0.200000,0.014000,0.000000,0.200000,0.000000,0.430000,5.000000,0.200000,...,0.200000,0.400000,0.000000,0.200000,0.000000,2.000000,1.551000,0.400000,0.500000,0.313100
50%,3.410000,0.760000,0.200000,0.166000,0.350000,0.200000,0.070000,1.300000,5.000000,0.200000,...,0.200000,0.400000,0.000000,0.200000,0.000000,2.200000,2.116000,0.400000,0.500000,0.482800
75%,55.570000,2.130000,0.600000,1.441500,3.325000,0.400000,1.507500,7.272500,5.000000,0.200000,...,0.200000,0.400000,0.000000,0.200000,0.000000,3.200000,10.076000,0.400000,0.500000,2.997300
max,59.850000,85.000000,0.600000,51.000000,1264.630000,0.600000,758.778000,1268.910000,9.000000,0.600000,...,0.600000,2.400000,9.000000,0.600000,5.400000,5.200000,801.262000,4.800000,0.500000,961.514400

# Klasifikasi

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [47]:
x = dummy.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [48]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [49]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [50]:
classifier = KNeighborsClassifier(n_neighbors=3, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[124   0]
 [  6  64]]
0.9690721649484536

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [51]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[124   0]
 [  7  63]]
0.9639175257731959

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [52]:
classifier = KNeighborsClassifier(n_neighbors=7, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[124   0]
 [ 13  57]]
0.9329896907216495

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [53]:
classifier = KNeighborsClassifier(n_neighbors=9, metric='euclidean')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[124   0]
 [ 14  56]]
0.9278350515463918

C:\Users\User\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)