In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("audit_10%.csv")

In [3]:
df

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,4.18,0.6,2.508,2.50,NaN,0.500,6.68,NaN,0.2,...,0.4,NaN,0.2,0.0,2.4,8.574,0.4,0.5,1.7148,1
1,3.89,0.00,NaN,0.000,4.83,NaN,0.966,4.83,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0
2,3.89,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096,0
3,3.89,0.00,0.2,0.000,10.80,0.6,6.480,10.80,6.0,0.6,...,0.4,0.0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060,1
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.08,5.0,0.2,...,0.4,0.0,NaN,0.0,NaN,1.416,NaN,NaN,0.2832,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520,NaN,0.32,0.2,0.064,0.00,0.2,0.000,0.32,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928,0
521,21.61,0.56,0.2,0.112,0.63,0.2,0.126,NaN,NaN,0.2,...,0.4,0.0,0.2,0.0,NaN,1.656,0.4,0.5,0.3312,0
522,21.61,0.54,0.2,0.108,0.56,0.2,NaN,1.10,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.780,0.4,0.5,0.3560,0
523,21.61,0.63,0.2,0.126,0.69,0.2,0.138,1.32,5.0,0.2,...,0.4,0.0,0.2,NaN,2.0,1.728,0.4,0.5,NaN,0
524,21.61,0.37,0.2,0.074,0.46,0.2,NaN,0.83,5.0,0.2,...,NaN,0.0,0.2,0.0,2.0,1.566,0.4,0.5,0.3132,0

In [4]:
df.dtypes

Sector_score      float64
PARA_A            float64
Score_A           float64
Risk_A            float64
PARA_B            float64
Score_B           float64
Risk_B            float64
TOTAL             float64
numbers           float64
Score_B.1         float64
Risk_C            float64
Money_Value       float64
Score_MV          float64
Risk_D            float64
District_Loss     float64
PROB              float64
RiSk_E            float64
History           float64
Prob              float64
Risk_F            float64
Score             float64
Inherent_Risk     float64
CONTROL_RISK      float64
Detection_Risk    float64
Audit_Risk        float64
Risk                int64
dtype: object

In [5]:
df.isnull().sum()

Sector_score      58
PARA_A            42
Score_A           50
Risk_A            56
PARA_B            51
Score_B           56
Risk_B            61
TOTAL             72
numbers           59
Score_B.1         70
Risk_C            57
Money_Value       45
Score_MV          52
Risk_D            53
District_Loss     56
PROB              44
RiSk_E            65
History           50
Prob              64
Risk_F            54
Score             57
Inherent_Risk     50
CONTROL_RISK      64
Detection_Risk    54
Audit_Risk        47
Risk               0
dtype: int64

In [6]:
null_counts = df.isnull().sum()
null_percentages = 100 * null_counts / len(df)
null_percentages

Sector_score      11.047619
PARA_A             8.000000
Score_A            9.523810
Risk_A            10.666667
PARA_B             9.714286
Score_B           10.666667
Risk_B            11.619048
TOTAL             13.714286
numbers           11.238095
Score_B.1         13.333333
Risk_C            10.857143
Money_Value        8.571429
Score_MV           9.904762
Risk_D            10.095238
District_Loss     10.666667
PROB               8.380952
RiSk_E            12.380952
History            9.523810
Prob              12.190476
Risk_F            10.285714
Score             10.857143
Inherent_Risk      9.523810
CONTROL_RISK      12.190476
Detection_Risk    10.285714
Audit_Risk         8.952381
Risk               0.000000
dtype: float64

In [7]:
null_counts = df.isnull().sum().sum()
total = df.size
null_percentages = 100 * null_counts / total
print("total nilai :",total)
print("nilai hilang :",null_counts)
print("persentase hilang :",null_percentages)

total nilai : 13650
nilai hilang : 1387
persentase hilang : 10.16117216117216

# Imputasi Median

In [8]:
df2 = df.fillna(df.median())

In [9]:
df2

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
0,3.89,4.18,0.6,2.508,2.50,0.2,0.500,6.68,5.0,0.2,...,0.4,0.0,0.2,0.0,2.4,8.574,0.4,0.5,1.7148,1
1,3.89,0.00,0.4,0.000,4.83,0.2,0.966,4.83,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,2.554,0.4,0.5,0.5108,0
2,3.89,0.51,0.2,0.102,0.23,0.2,0.046,0.74,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.548,0.4,0.5,0.3096,0
3,3.89,0.00,0.2,0.000,10.80,0.6,6.480,10.80,6.0,0.6,...,0.4,0.0,0.2,0.0,4.4,17.530,0.4,0.5,3.5060,1
4,3.89,0.00,0.2,0.000,0.08,0.2,0.016,0.08,5.0,0.2,...,0.4,0.0,0.2,0.0,2.6,1.416,0.4,0.5,0.2832,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520,2.72,0.32,0.2,0.064,0.00,0.2,0.000,0.32,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.464,0.4,0.5,0.2928,0
521,21.61,0.56,0.2,0.112,0.63,0.2,0.126,2.49,5.0,0.2,...,0.4,0.0,0.2,0.0,2.6,1.656,0.4,0.5,0.3312,0
522,21.61,0.54,0.2,0.108,0.56,0.2,0.167,1.10,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.780,0.4,0.5,0.3560,0
523,21.61,0.63,0.2,0.126,0.69,0.2,0.138,1.32,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.728,0.4,0.5,1.3032,0
524,21.61,0.37,0.2,0.074,0.46,0.2,0.167,0.83,5.0,0.2,...,0.4,0.0,0.2,0.0,2.0,1.566,0.4,0.5,0.3132,0

In [10]:
df2.describe()

,Sector_score,PARA_A,Score_A,Risk_A,PARA_B,Score_B,Risk_B,TOTAL,numbers,Score_B.1,...,RiSk_E,History,Prob,Risk_F,Score,Inherent_Risk,CONTROL_RISK,Detection_Risk,Audit_Risk,Risk
count,525.000000,525.000000,525.000000,525.000000,525.000000,525.000000,525.000000,525.000000,525.000000,525.000000,...,525.000000,525.000000,525.000000,525.000000,525.000000,525.000000,525.000000,525.0,525.000000,525.000000
mean,3.686419,3.220248,0.402667,1.834907,12.051756,0.325333,8.465353,16.497632,5.083810,0.229333,...,0.526476,0.137143,0.220952,0.065524,2.893714,19.440309,0.586667,0.5,8.643385,0.525714
std,3.992920,6.642381,0.170519,4.041718,24.956461,0.175792,36.059202,60.771393,0.298892,0.090675,...,0.304427,0.624142,0.074771,0.346372,0.869796,44.133407,0.479716,0.0,44.738614,0.499815
min,1.850000,0.000000,0.200000,0.000000,0.000000,0.200000,0.000000,0.000000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.000000,1.400000,0.400000,0.5,0.280000,0.000000
25%,1.990000,0.560000,0.200000,0.118000,0.050000,0.200000,0.010000,1.100000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.200000,1.966000,0.400000,0.5,0.397600,0.000000
50%,2.720000,1.350000,0.400000,0.564000,0.825000,0.200000,0.167000,2.490000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,2.600000,3.790000,0.400000,0.5,1.303200,1.000000
75%,3.890000,3.620000,0.600000,2.172000,6.800000,0.600000,3.516000,10.970000,5.000000,0.200000,...,0.400000,0.000000,0.200000,0.000000,3.600000,19.732000,0.400000,0.5,5.756800,1.000000
max,21.610000,85.000000,0.600000,51.000000,144.390000,0.600000,758.778000,1268.910000,9.000000,0.600000,...,2.400000,9.000000,0.600000,5.400000,5.200000,583.688000,5.800000,0.5,961.514400,1.000000

# Klasifikasi

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [12]:
x = df2.iloc[:, :-1].values
y = df2.iloc[:, -1].values

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=15)

In [14]:
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [15]:
classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(cm)
print(accuracy)

[[58  2]
 [ 5 67]]
0.946969696969697